# * Default Configuration Properties *
# - Modify as needed for PAS instance -
#
pasoe.instance.name=${pasoeInstanceName}
primary.ablapp.name=${oearPrimaryAblAppName}
primary.webapp.name=${oearPrimaryWebAppName}
monitor.ablapp.name=${oearMonitorAblAppName}
monitor.webapp.name=${oearMonitorWebAppName}
#
application.api.version=${apiVersion}
#
application.domain.name=${pasoeDomainName}
application.domain.code=${pasoeDomainCode}
#
application.realm.user=${pasoeRealmUser}
application.realm.code=${pasoeRealmCode}
#
application.port.http=${pasoeInstanceHttp}
application.port.https=${pasoeInstanceHttps}
application.port.ajp=${pasoeInstanceAjp}
application.port.shut=${pasoeInstanceShut}
application.port.health=${pasoeInstanceHealth}
#
application.db.skip=${skipDatabaseInstall}
application.db.name=${appDatabaseName}
application.db.host.name=${dbHostName}
application.db.port.service=${dbPortService}
application.db.port.min=${dbPortMin}
application.db.port.max=${dbPortMax}
application.db.lockwait=${dbLockWait}
application.db.codepage=ISO8859-1
application.db.collation=Basic
#
tomcat.management.user=${pasoeManagerUser}
tomcat.management.code=${pasoeManagerCode}
#
tomcat.executor.threads=${tomcatExecutorThreads}
tomcat.executor.minspare=${tomcatMinSpareThreads}
#
tomcat.queue.size=${tomcatMaxQueueSize}
#
tomcat.uri.encoding=${tomcatUriEncoding}
#
tomcat.jvm.xmx.mb=${tomcatJvmXmxMb}
tomcat.jvm.xms.mb=${tomcatJvmXmsMb}
tomcat.jvm.newsize.mb=${tomcatJvmNewSizeMb}
