http.all.authmanager=oerealm
client.login.model=form

OEClientPrincipalFilter.domain=@DOMAIN@
OEClientPrincipalFilter.roles=EndUser
OEClientPrincipalFilter.enabled=true
OEClientPrincipalFilter.anonymous=true
OEClientPrincipalFilter.sealAnonymous=true
OEClientPrincipalFilter.passthru=true

OEClientPrincipalFilter.properties.1.key=fldAuthType
OEClientPrincipalFilter.properties.1.value=${client.login.model}
OEClientPrincipalFilter.properties.2.key=fldAppType
OEClientPrincipalFilter.properties.2.value=Testing
OEClientPrincipalFilter.properties.3.key=Product
OEClientPrincipalFilter.properties.3.value=LoadSuite

OERealm.AuthProvider.multiTenant=true
OERealm.AuthProvider.userDomain=@DOMAIN@
OERealm.AuthProvider.expires=86400
OERealm.AuthProvider.genInternalSession=true

OERealm.UserDetails.realmClass=OpenEdge.LoadSuite.Security.Realm.HybridRealm
OERealm.UserDetails.grantedAuthorities=ROLE_NoAccess
OERealm.UserDetails.appendRealmError=false
OERealm.UserDetails.realmTokenFile=RealmToken.cp

OERealm.AuthProvider.properties.1.key=fldAuthType
OERealm.AuthProvider.properties.1.value=${client.login.model}
OERealm.AuthProvider.properties.2.key=fldAppType
OERealm.AuthProvider.properties.2.value=Testing
OERealm.AuthProvider.properties.3.key=Product
OERealm.AuthProvider.properties.3.value=LoadSuite
