/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttBenefits.i
 Created : 10/18/2022 15:17:25.282+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttBenefits no-undo
                    before-table bfttBenefits
   field DependentCare as int64 
   field EmpNum as int64 
   field HealthCare as character 
   field LifeInsurance as int64 
   field MedicalSpending as int64 
   field Pension401K as int64 
   field StockPurchase as int64 
   index EmpNo is unique 
      is primary
     EmpNum ascending
.
