/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttBin.i
 Created : 10/18/2022 15:17:25.283+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttBin no-undo
                    before-table bfttBin
   field BinName as character 
   field BinNum as int64 
   field ItemNum as int64 
   field Qty as int64 
   field WarehouseNum as int64 
   index BinNum is unique 
      is primary
     BinNum ascending
.
