/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttBillTo.i
 Created : 10/18/2022 15:17:25.282+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttBillTo no-undo
                    before-table bfttBillTo
   field Address as character 
   field Address2 as character 
   field BillToID as int64 
   field City as character 
   field Contact as character 
   field CustNum as int64 
   field Name as character 
   field Phone as character 
   field PostalCode as character 
   field State as character 
   index CustNumBillTo is unique 
      is primary
     CustNum ascending
     BillToID ascending
.
