/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttCustomer.i
 Created : 10/18/2022 15:17:25.284+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttCustomer no-undo
                    before-table bfttCustomer
   field Address as character 
   field Address2 as character 
   field Balance as decimal 
   field City as character 
   field Comments as character 
   field Contact as character 
   field Country as character 
   field CreditLimit as decimal 
   field CustNum as int64 
   field Discount as int64 
   field EmailAddress as character 
   field Fax as character 
   field Name as character 
   field Phone as character 
   field PostalCode as character 
   field SalesRep as character 
   field State as character 
   field Terms as character 
   index CustNum is unique 
      is primary
     CustNum ascending
.
