/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttDepartment.i
 Created : 10/18/2022 15:17:25.288+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttDepartment no-undo
                    before-table bfttDepartment
   field DeptCode as character 
   field DeptName as character 
   index DeptCode is unique 
      is primary
     DeptCode ascending
.
