/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttEmployee.i
 Created : 10/18/2022 15:17:25.288+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttEmployee no-undo
                    before-table bfttEmployee
   field Address as character 
   field Address2 as character 
   field BirthDate as date 
   field City as character 
   field DeptCode as character 
   field EmpNum as int64 
   field FirstName as character 
   field HomePhone as character 
   field LastName as character 
   field Position as character 
   field PostalCode as character 
   field SickDaysLeft as int64 
   field StartDate as date 
   field State as character 
   field VacationDaysLeft as int64 
   field WorkPhone as character 
   index EmpNo is unique 
      is primary
     EmpNum ascending
   index Name is unique 
     LastName ascending
     FirstName ascending
.
