/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttFamily.i
 Created : 10/18/2022 15:17:25.290+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttFamily no-undo
                    before-table bfttFamily
   field BenefitDate as date 
   field BirthDate as date 
   field CoveredOnBenefits as logical 
   field EmpNum as int64 
   field Relation as character 
   field RelativeName as character 
   index EmpNoRelativeName is unique 
      is primary
     EmpNum ascending
     RelativeName ascending
.
