/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttFeedback.i
 Created : 10/18/2022 15:17:25.291+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttFeedback no-undo
                    before-table bfttFeedback
   field Comments as character 
   field Company as character 
   field Contact as character 
   field Department as character 
   field EmailAddress as character 
   field Fax as character 
   field Phone as character 
   field Rating as int64 
.
