/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttInvoice.i
 Created : 10/18/2022 15:17:25.292+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttInvoice no-undo
                    before-table bfttInvoice
   field Adjustment as decimal 
   field Amount as decimal 
   field CustNum as int64 
   field InvoiceDate as date 
   field InvoiceNum as int64 
   field OrderNum as int64 
   field ShipCharge as decimal 
   field TotalPaid as decimal 
   index InvoiceNum is unique 
      is primary
     InvoiceNum ascending
.
