/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttInventoryTrans.i
 Created : 10/18/2022 15:17:25.291+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttInventoryTrans no-undo
                    before-table bfttInventoryTrans
   field BinNum as int64 
   field InvTransNum as int64 
   field InvType as character 
   field ItemNum as int64 
   field OrderNum as int64 
   field PONum as int64 
   field Qty as int64 
   field TransDate as date 
   field TransTime as character 
   field WarehouseNum as int64 
.
