/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttItem.i
 Created : 10/18/2022 15:17:25.293+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttItem no-undo
                    before-table bfttItem
   field Allocated as int64 
   field CatDescription as character 
   field Category1 as character 
   field Category2 as character 
   field CatPage as int64 
   field ItemImage as blob 
   field ItemName as character 
   field ItemNum as int64 
   field MinQty as int64 
   field OnHand as int64 
   field OnOrder as int64 
   field Price as decimal 
   field ReOrder as int64 
   field Special as character 
   field Weight as decimal 
   index ItemNum is unique 
      is primary
     ItemNum ascending
.
