/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttLocalDefault.i
 Created : 10/18/2022 15:17:25.294+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttLocalDefault no-undo
                    before-table bfttLocalDefault
   field Country as character 
   field CurrencySymbol as character 
   field DateFormat as character 
   field LocalDefNum as int64 
   field PostalFormat as character 
   field PostalLabel as character 
   field Region1Label as character 
   field Region2Label as character 
   field TelFormat as character 
   index LocalDefNum is unique 
      is primary
     LocalDefNum ascending
.
