/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttOrder.i
 Created : 10/18/2022 15:17:25.294+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttOrder no-undo
                    before-table bfttOrder
   field BillToID as int64 
   field Carrier as character 
   field CreditCard as character 
   field CustNum as int64 
   field Instructions as character 
   field OrderDate as date 
   field OrderNum as int64 
   field OrderStatus as character 
   field PO as character 
   field PromiseDate as date 
   field SalesRep as character 
   field ShipDate as date 
   field ShipToID as int64 
   field Terms as character 
   field WarehouseNum as int64 
   index CustOrder is unique 
      is primary
     CustNum ascending
     OrderNum ascending
   index OrderNum is unique 
     OrderNum ascending
.
