/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttOrderLine.i
 Created : 10/18/2022 15:17:25.296+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttOrderLine no-undo
                    before-table bfttOrderLine
   field Discount as int64 
   field ExtendedPrice as decimal 
   field ItemNum as int64 
   field LineNum as int64 
   field OrderLineStatus as character 
   field OrderNum as int64 
   field Price as decimal 
   field Qty as int64 
   index OrderLine is unique 
      is primary
     OrderNum ascending
     LineNum ascending
.
