/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttPOLine.i
 Created : 10/18/2022 15:17:25.297+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttPOLine no-undo
                    before-table bfttPOLine
   field Discount as int64 
   field ExtendedPrice as decimal 
   field ItemNum as int64 
   field LineNum as int64 
   field POLineStatus as character 
   field PONum as int64 
   field Price as decimal 
   field Qty as int64 
   index PONumLineNum is unique 
      is primary
     PONum ascending
     LineNum ascending
.
