/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttPurchaseOrder.i
 Created : 10/18/2022 15:17:25.297+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttPurchaseOrder no-undo
                    before-table bfttPurchaseOrder
   field DateEntered as date 
   field PONum as int64 
   field POStatus as character 
   field ReceiveDate as date 
   field SupplierIDNum as int64 
   index PONum is unique 
      is primary
     PONum ascending
.
