/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttRefCall.i
 Created : 10/18/2022 15:17:25.298+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttRefCall no-undo
                    before-table bfttRefCall
   field CallDate as date 
   field CallNum as character 
   field CustNum as int64 
   field Parent as character 
   field SalesRep as character 
   field Txt as character 
   index CallNum is unique 
      is primary
     CallNum ascending
   index CustNum is unique 
     CustNum ascending
     CallNum ascending
   index Sibling is unique 
     Parent ascending
     CallNum ascending
.
