/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttSalesRep.i
 Created : 10/18/2022 15:17:25.300+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttSalesRep no-undo
                    before-table bfttSalesRep
   field MonthQuota as int64 extent 12
   field Region as character 
   field RepName as character 
   field SalesRep as character 
   index SalesRep is unique 
      is primary
     SalesRep ascending
.
