/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttShipTo.i
 Created : 10/18/2022 15:17:25.301+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttShipTo no-undo
                    before-table bfttShipTo
   field Address as character 
   field Address2 as character 
   field City as character 
   field Comments as character 
   field Contact as character 
   field CustNum as int64 
   field Name as character 
   field Phone as character 
   field PostalCode as character 
   field ShipToID as int64 
   field State as character 
   index CustNumShipTo is unique 
      is primary
     CustNum ascending
     ShipToID ascending
.
