/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttState.i
 Created : 10/18/2022 15:17:25.302+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttState no-undo
                    before-table bfttState
   field Region as character 
   field State as character 
   field StateName as character 
   index State is unique 
      is primary
     State ascending
.
