/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttSupplier.i
 Created : 10/18/2022 15:17:25.302+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttSupplier no-undo
                    before-table bfttSupplier
   field Address as character 
   field Address2 as character 
   field City as character 
   field Comments as character 
   field Country as character 
   field Discount as int64 
   field LoginDate as date 
   field Name as character 
   field Password as character 
   field Phone as character 
   field PostalCode as character 
   field ShipAmount as int64 
   field State as character 
   field SupplierIDNum as int64 
   index SupplierID is unique 
      is primary
     SupplierIDNum ascending
.
