/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttSupplierItemXref.i
 Created : 10/18/2022 15:17:25.303+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttSupplierItemXref no-undo
                    before-table bfttSupplierItemXref
   field ItemNum as int64 
   field SupplierIDNum as int64 
   index ItemNumSupplierID is unique 
      is primary
     ItemNum ascending
     SupplierIDNum ascending
   index SupplieridItemNum is unique 
     SupplierIDNum ascending
     ItemNum ascending
.
