/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttTimeSheet.i
 Created : 10/18/2022 15:17:25.305+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttTimeSheet no-undo
                    before-table bfttTimeSheet
   field AMTimeIn as character 
   field AMTimeOut as character 
   field DayRecorded as date 
   field EmpNum as int64 
   field OvertimeHours as decimal 
   field PMTimeIn as character 
   field PMTimeOut as character 
   field RegularHours as decimal 
   field TypeRecorded as character 
   index EmpNoDayRecorded is unique 
      is primary
     EmpNum ascending
     DayRecorded ascending
.
