/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttVacation.i
 Created : 10/18/2022 15:17:25.306+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttVacation no-undo
                    before-table bfttVacation
   field EmpNum as int64 
   field EndDate as date 
   field StartDate as date 
   index EmpNoStartDate is unique 
      is primary
     EmpNum ascending
     StartDate ascending
.
