/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/tt/ttWarehouse.i
 Created : 10/18/2022 15:17:25.307+00:00
 Generated by TempTableBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

define  temp-table ttWarehouse no-undo
                    before-table bfttWarehouse
   field Address as character 
   field Address2 as character 
   field City as character 
   field Country as character 
   field Phone as character 
   field PostalCode as character 
   field State as character 
   field WarehouseName as character 
   field WarehouseNum as int64 
   index WarehouseNum is unique 
      is primary
     WarehouseNum ascending
.
