/* ----------------------------------------------------------------------
 File : /Function/record/read/general.p
 Created : 11/10/2022 20:53:18.701+00:00
 Generated by DatabaseBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

using OpenEdge.Core.Assert.

function readBenefits returns logical (input inEmpNum as integer):
   Assert:NotZero(inEmpNum).
   find first Benefits no-lock
      where Benefits.EmpNum = inEmpNum
      no-error.
   Assert:IsTrue(available Benefits).
end. //Benefits

function readBillTo returns logical (input inCustNum as integer,input inBillToID as integer):
   Assert:NotZero(inBillToID).
   Assert:NotZero(inCustNum).
   find first BillTo no-lock
      where BillTo.BillToID = inBillToID
      and   BillTo.CustNum = inCustNum
      no-error.
   Assert:IsTrue(available BillTo).
end. //BillTo

function readBin returns logical (input inBinNum as integer):
   Assert:NotZero(inBinNum).
   find first Bin no-lock
      where Bin.BinNum = inBinNum
      no-error.
   Assert:IsTrue(available Bin).
end. //Bin

function readCustomer returns logical (input inCustNum as integer):
   Assert:NotZero(inCustNum).
   find first Customer no-lock
      where Customer.CustNum = inCustNum
      no-error.
   Assert:IsTrue(available Customer).
end. //Customer

function readDepartment returns logical (input inDeptCode as character,input inDeptName as character):
   Assert:NotNullOrEmpty(inDeptCode).
   find first Department no-lock
      where Department.DeptCode = inDeptCode
      no-error.
   Assert:IsTrue(available Department).
end. //Department

function readEmployee returns logical (input inEmpNum as integer):
   Assert:NotZero(inEmpNum).
   find first Employee no-lock
      where Employee.EmpNum = inEmpNum
      no-error.
   Assert:IsTrue(available Employee).
end. //Employee

function readFamily returns logical (input inEmpNum as integer,input inRelativeName as character):
   Assert:NotZero(inEmpNum).
   Assert:NotNullOrEmpty(inRelativeName).
   find first Family no-lock
      where Family.EmpNum = inEmpNum
      and   Family.RelativeName = inRelativeName
      no-error.
   Assert:IsTrue(available Family).
end. //Family

function readFeedback returns logical (input inDepartment as character,input inComments as character):
   Assert:NotNullOrEmpty(inDepartment).
   find first Feedback no-lock
      where Feedback.Department = inDepartment
      no-error.
   Assert:IsTrue(available Feedback).
end. //Feedback

function readInventoryTrans returns logical (input inInvTransNum as integer):
   Assert:NotZero(inInvTransNum).
   find first InventoryTrans no-lock
      where InventoryTrans.InvTransNum = inInvTransNum
      no-error.
   Assert:IsTrue(available InventoryTrans).
end. //InventoryTrans

function readInvoice returns logical (input inInvoiceNum as integer,input inAmount as decimal):
   Assert:NotZero(inInvoiceNum).
   find first Invoice no-lock
      where Invoice.InvoiceNum = inInvoiceNum
      no-error.
   Assert:IsTrue(available Invoice).
end. //Invoice

function readItem returns logical (input inItemNum as integer):
   Assert:NotZero(inItemNum).
   find first Item no-lock
      where Item.ItemNum = inItemNum
      no-error.
   Assert:IsTrue(available Item).
end. //Item

function readLocalDefault returns logical (input inLocalDefNum as integer):
   Assert:NotZero(inLocalDefNum).
   find first LocalDefault no-lock
      where LocalDefault.LocalDefNum = inLocalDefNum
      no-error.
   Assert:IsTrue(available LocalDefault).
end. //LocalDefault

function readOrder returns logical (input inOrderNum as integer):
   Assert:NotZero(inOrderNum).
   find first Order no-lock
      where Order.OrderNum = inOrderNum
      no-error.
   Assert:IsTrue(available Order).
end. //Order

function readOrderLine returns logical (input inLineNum as integer,input inOrderNum as integer):
   Assert:NotZero(inLineNum).
   Assert:NotZero(inOrderNum).
   find first OrderLine no-lock
      where OrderLine.LineNum = inLineNum
      and   OrderLine.OrderNum = inOrderNum
      no-error.
   Assert:IsTrue(available OrderLine).
end. //OrderLine

function readPOLine returns logical (input inLineNum as integer,input inPONum as integer):
   Assert:NotZero(inLineNum).
   Assert:NotZero(inPONum).
   find first POLine no-lock
      where POLine.LineNum = inLineNum
      and   POLine.PONum = inPONum
      no-error.
   Assert:IsTrue(available POLine).
end. //POLine

function readPurchaseOrder returns logical (input inPONum as integer):
   Assert:NotZero(inPONum).
   find first PurchaseOrder no-lock
      where PurchaseOrder.PONum = inPONum
      no-error.
   Assert:IsTrue(available PurchaseOrder).
end. //PurchaseOrder

function readRefCall returns logical (input inCallNum as integer):
   Assert:NotZero(inCallNum).
   find first RefCall no-lock
      where RefCall.CallNum = inCallNum
      no-error.
   Assert:IsTrue(available RefCall).
end. //RefCall

function readSalesRep returns logical (input inSalesRep as character,input inRepName as character):
   Assert:NotNullOrEmpty(inSalesRep).
   find first SalesRep no-lock
      where SalesRep.SalesRep = inSalesRep
      no-error.
   Assert:IsTrue(available SalesRep).
end. //SalesRep

function readShipTo returns logical (input inCustNum as integer,input inShipToID as integer):
   Assert:NotZero(inCustNum).
   Assert:NotZero(inShipToID).
   find first ShipTo no-lock
      where ShipTo.CustNum = inCustNum
      and   ShipTo.ShipToID = inShipToID
      no-error.
   Assert:IsTrue(available ShipTo).
end. //ShipTo

function readState returns logical (input inState as character,input inStateName as character):
   Assert:NotNullOrEmpty(inState).
   find first State no-lock
      where State.State = inState
      no-error.
   Assert:IsTrue(available State).
end. //State

function readSupplier returns logical (input inSupplierIDNum as integer):
   Assert:NotZero(inSupplierIDNum).
   find first Supplier no-lock
      where Supplier.SupplierIDNum = inSupplierIDNum
      no-error.
   Assert:IsTrue(available Supplier).
end. //Supplier

function readSupplierItemXref returns logical (input inSupplierIDNum as integer,input inItemNum as integer):
   Assert:NotZero(inItemNum).
   Assert:NotZero(inSupplierIDNum).
   find first SupplierItemXref no-lock
      where SupplierItemXref.ItemNum = inItemNum
      and   SupplierItemXref.SupplierIDNum = inSupplierIDNum
      no-error.
   Assert:IsTrue(available SupplierItemXref).
end. //SupplierItemXref

function readTimeSheet returns logical (input inDayRecorded as date,input inEmpNum as integer):
   Assert:NotNull(inDayRecorded).
   Assert:NotZero(inEmpNum).
   find first TimeSheet no-lock
      where TimeSheet.DayRecorded = inDayRecorded
      and   TimeSheet.EmpNum = inEmpNum
      no-error.
   Assert:IsTrue(available TimeSheet).
end. //TimeSheet

function readVacation returns logical (input inEmpNum as integer,input inStartDate as date):
   Assert:NotZero(inEmpNum).
   Assert:NotNull(inStartDate).
   find first Vacation no-lock
      where Vacation.EmpNum = inEmpNum
      and   Vacation.StartDate = inStartDate
      no-error.
   Assert:IsTrue(available Vacation).
end. //Vacation

function readWarehouse returns logical (input inWarehouseNum as integer):
   Assert:NotZero(inWarehouseNum).
   find first Warehouse no-lock
      where Warehouse.WarehouseNum = inWarehouseNum
      no-error.
   Assert:IsTrue(available Warehouse).
end. //Warehouse

