/* ----------------------------------------------------------------------
 File : /Function/record/create/general.p
 Created : 11/10/2022 20:53:18.675+00:00
 Generated by DatabaseBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

using OpenEdge.Core.Assert.

function createBenefits returns logical (input inEmpNum as integer):
   Assert:NotZero(inEmpNum).

   do transaction:
        create Benefits.
        assign
            Benefits.EmpNum = inEmpNum
            .
   end. //transaction
end. //Benefits

function createBillTo returns logical (input inCustNum as integer,input inBillToID as integer,input inName as character):
   Assert:NotZero(inBillToID).
   Assert:NotZero(inCustNum).

   do transaction:
        create BillTo.
        assign
            BillTo.BillToID = inBillToID
            BillTo.CustNum = inCustNum
            BillTo.Name = inName
            .
   end. //transaction
end. //BillTo

function createBin returns logical (input inBinName as character):

   do transaction:
        create Bin.
        assign
            Bin.BinName = inBinName
            .
   end. //transaction
end. //Bin

function createCustomer returns logical (input inCustNum as integer,input inName as character,input inComments as character):

   do transaction:
        create Customer.
        assign
            Customer.Comments = inComments
            Customer.Name = inName
            .
   end. //transaction
end. //Customer

function createDepartment returns logical (input inDeptCode as character,input inDeptName as character):
   Assert:NotNullOrEmpty(inDeptCode).

   do transaction:
        create Department.
        assign
            Department.DeptCode = inDeptCode
            Department.DeptName = inDeptName
            .
   end. //transaction
end. //Department

function createEmployee returns logical (input inFirstName as character,input inLastName as character):
   Assert:NotNullOrEmpty(inFirstName).
   Assert:NotNullOrEmpty(inLastName).

   do transaction:
        create Employee.
        assign
            Employee.FirstName = inFirstName
            Employee.LastName = inLastName
            .
   end. //transaction
end. //Employee

function createFamily returns logical (input inEmpNum as integer,input inRelativeName as character):
   Assert:NotZero(inEmpNum).
   Assert:NotNullOrEmpty(inRelativeName).

   do transaction:
        create Family.
        assign
            Family.EmpNum = inEmpNum
            Family.RelativeName = inRelativeName
            .
   end. //transaction
end. //Family

function createFeedback returns logical (input inDepartment as character,input inComments as character):
   Assert:NotNullOrEmpty(inDepartment).

   do transaction:
        create Feedback.
        assign
            Feedback.Department = inDepartment
            Feedback.Comments = inComments
            .
   end. //transaction
end. //Feedback

function createInventoryTrans returns logical (input inInvTransNum as integer):

   do transaction:
        create InventoryTrans.
        assign
            .
   end. //transaction
end. //InventoryTrans

function createInvoice returns logical (input inInvoiceNum as integer,input inAmount as decimal):

   do transaction:
        create Invoice.
        assign
            Invoice.Amount = inAmount
            .
   end. //transaction
end. //Invoice

function createItem returns logical (input inItemNum as integer,input inItemName as character,input inCatDescription as character):

   do transaction:
        create Item.
        assign
            Item.CatDescription = inCatDescription
            Item.ItemName = inItemName
            .
   end. //transaction
end. //Item

function createLocalDefault returns logical (input inLocalDefNum as integer):

   do transaction:
        create LocalDefault.
        assign
            .
   end. //transaction
end. //LocalDefault

function createOrder returns logical (input inOrderNum as integer,input inCustNum as integer):
   Assert:NotZero(inCustNum).

   do transaction:
        create Order.
        assign
            Order.CustNum = inCustNum
            .
   end. //transaction
end. //Order

function createOrderLine returns logical (input inLineNum as integer,input inOrderNum as integer):
   Assert:NotZero(inLineNum).
   Assert:NotZero(inOrderNum).

   do transaction:
        create OrderLine.
        assign
            OrderLine.LineNum = inLineNum
            OrderLine.OrderNum = inOrderNum
            .
   end. //transaction
end. //OrderLine

function createPOLine returns logical (input inLineNum as integer,input inPONum as integer):
   Assert:NotZero(inLineNum).
   Assert:NotZero(inPONum).

   do transaction:
        create POLine.
        assign
            POLine.LineNum = inLineNum
            POLine.PONum = inPONum
            .
   end. //transaction
end. //POLine

function createPurchaseOrder returns logical (input inPONum as integer):

   do transaction:
        create PurchaseOrder.
        assign
            .
   end. //transaction
end. //PurchaseOrder

function createRefCall returns logical (input inCallNum as integer,input inCustNum as integer,input inParent as character):
   Assert:NotZero(inCallNum).
   Assert:NotZero(inCustNum).
   Assert:NotNullOrEmpty(inParent).

   do transaction:
        create RefCall.
        assign
            RefCall.CallNum = inCallNum
            RefCall.CustNum = inCustNum
            RefCall.Parent = inParent
            .
   end. //transaction
end. //RefCall

function createSalesRep returns logical (input inSalesRep as character,input inRepName as character):
   Assert:NotNullOrEmpty(inSalesRep).

   do transaction:
        create SalesRep.
        assign
            SalesRep.SalesRep = inSalesRep
            SalesRep.RepName = inRepName
            .
   end. //transaction
end. //SalesRep

function createShipTo returns logical (input inCustNum as integer,input inShipToID as integer,input inName as character,input inComments as character):
   Assert:NotZero(inCustNum).
   Assert:NotZero(inShipToID).

   do transaction:
        create ShipTo.
        assign
            ShipTo.CustNum = inCustNum
            ShipTo.ShipToID = inShipToID
            ShipTo.Comments = inComments
            ShipTo.Name = inName
            .
   end. //transaction
end. //ShipTo

function createState returns logical (input inState as character,input inStateName as character):
   Assert:NotNullOrEmpty(inState).

   do transaction:
        create State.
        assign
            State.State = inState
            State.StateName = inStateName
            .
   end. //transaction
end. //State

function createSupplier returns logical (input inSupplierIDNum as integer,input inName as character,input inShipAmount as integer,input inComments as character):

   do transaction:
        create Supplier.
        assign
            Supplier.Comments = inComments
            Supplier.Name = inName
            Supplier.ShipAmount = inShipAmount
            .
   end. //transaction
end. //Supplier

function createSupplierItemXref returns logical (input inItemNum as integer,input inSupplierIDNum as integer):
   Assert:NotZero(inItemNum).
   Assert:NotZero(inSupplierIDNum).

   do transaction:
        create SupplierItemXref.
        assign
            SupplierItemXref.ItemNum = inItemNum
            SupplierItemXref.SupplierIDNum = inSupplierIDNum
            .
   end. //transaction
end. //SupplierItemXref

function createTimeSheet returns logical (input inDayRecorded as date,input inEmpNum as integer):
   Assert:NotNull(inDayRecorded).
   Assert:NotZero(inEmpNum).

   do transaction:
        create TimeSheet.
        assign
            TimeSheet.DayRecorded = inDayRecorded
            TimeSheet.EmpNum = inEmpNum
            .
   end. //transaction
end. //TimeSheet

function createVacation returns logical (input inEmpNum as integer,input inStartDate as date):
   Assert:NotZero(inEmpNum).
   Assert:NotNull(inStartDate).

   do transaction:
        create Vacation.
        assign
            Vacation.EmpNum = inEmpNum
            Vacation.StartDate = inStartDate
            .
   end. //transaction
end. //Vacation

function createWarehouse returns logical (input inWarehouseName as character):

   do transaction:
        create Warehouse.
        assign
            Warehouse.WarehouseName = inWarehouseName
            .
   end. //transaction
end. //Warehouse

