#
b .
#
d "Schema Area":6,64;1 .
#
a .
#
d "Data Area":10,256;8 .
#
d "Index Area":20,32;8 .
#
d "LOB Area":30,32;8 .
#
d "Audit Data Area":40,256;8 .
#
d "Audit Index Area":50,32;8 .
#
d "Change Data Area":60,256;8 .
#
d "Change Index Area":70,32;8 .
#
d "Audit Header Data Area":110,128;512 .
#
d "Audit Header Index Area":115,128;512 .
#
d "Audit Detail Data Area":120,128;512 .
#
d "Audit Detail Index Area":125,128;512 .
#
d "Replication Data Area":250,128;8 .
#
d "Replication Index Area":255,128;8 .
#
d "Context Data Area":280,128;8 .
#
d "Context Index Area":285,128;8 .
#
d "System Data Area":290,128;8 .
#
d "System Index Area":295,128;8 .
#
e "Encryption Policy Area":80,32;8 .

