/**************************************************************************************************************************
Copyright (c) 2026 by Progress Software Corporation and/or one of its subsidiaries or affiliates. All rights reserved.
***************************************************************************************************************************/
/*------------------------------------------------------------------------
    File        : IStandardService
    Purpose     : Common service interface class
    Description :
    Author(s)   : Dustin Grau
    Created     : Wed Dec 18 09:07:38 EST 2024
    Notes       :
------------------------------------------------------------------------*/

// Define the name of the class package for this application.
&GLOBAL-DEFINE CLASS_PACKAGE OpenEdge.Workshop

interface {&CLASS_PACKAGE}.Interface.IStandardService:


end interface.