http.all.authmanager=oerealm
client.login.model=form

OEClientPrincipalFilter.domain=@DOMAIN@
OEClientPrincipalFilter.roles=EndUser
OEClientPrincipalFilter.enabled=true
OEClientPrincipalFilter.anonymous=true
OEClientPrincipalFilter.sealAnonymous=true
OEClientPrincipalFilter.passthru=true

OERealm.AuthProvider.multiTenant=true
OERealm.AuthProvider.userDomain=@DOMAIN@
OERealm.AuthProvider.expires=86400
OERealm.AuthProvider.genInternalSession=true

OERealm.UserDetails.realmClass=OpenEdge.Workshop.Security.Realm.HybridRealm
OERealm.UserDetails.grantedAuthorities=ROLE_NoAccess
OERealm.UserDetails.appendRealmError=false
OERealm.UserDetails.realmTokenFile=RealmToken.cp
