[@PRIMARY_ABLAPP@]
    webApps=@PRIMARY_WEBAPP@

[AppServer.Agent.@PRIMARY_ABLAPP@]
    numInitialSessions=@NUM_INITIAL_SESSIONS@
    minAvailableABLSessions=@NUM_MIN_AVAIL_SESSIONS@
    PROPATH=${CATALINA_BASE}/ablapps/@PRIMARY_ABLAPP@/openedge,${CATALINA_BASE}/openedge,${CATALINA_BASE}/ablapps/@PRIMARY_ABLAPP@/openedge/@CLASSPACKAGE@.apl,${DLC}/tty,${DLC}/tty/netlib/OpenEdge.Net.apl
    sessionStartupProc=@CLASSPATH@/Common/Util/SessionStartup.p
    sessionStartupProcParam={"dbName": "@DBNAME@", "dbPath": "CATALINA_BASE/db"}
    sessionActivateProc=@CLASSPATH@/Common/Util/SessionActivate.p

[AppServer.SessMgr.@PRIMARY_ABLAPP@]
    agentLogEntryTypes=ASPlumbing,DB.Connects
    agentLogFile=${catalina.base}/logs/@PRIMARY_ABLAPP@.agent.{yyyy-mm-dd}.log
    agentStartupParam=-T "${catalina.base}/temp" -pf "${catalina.base}/ablapps/@PRIMARY_ABLAPP@/openedge/startup.pf"
    maxAgents=@NUM_MSAGENTS_MAX@
    minAgents=@NUM_MSAGENTS_MIN@
    numInitialAgents=@NUM_MSAGENTS_MIN@
    maxConnectionsPerAgent=@NUM_AGENT_CONNS@
    maxABLSessionsPerAgent=@NUM_ABL_SESSIONS@

[@PRIMARY_ABLAPP@.@PRIMARY_WEBAPP@]
    allowRuntimeUpdates=1
    collectMetrics=3
    statusEnabled=1

[@PRIMARY_ABLAPP@.@PRIMARY_WEBAPP@.APSV]
    adapterEnabled=1
    enableRequestChunking=1
    oepingEnabled=1
    oepingProcedure=
    serviceFaultLevel=1
    useHTTPSessions=1

[@PRIMARY_ABLAPP@.@PRIMARY_WEBAPP@.SOAP]
    adapterEnabled=0
    adminEnabled=0
    adminSoapAction=urn:services-progress-com:wsa-admin:01
    debugClients=
    wsaUrl=http://${psc.as.host.name}:${psc.as.http.port}/@PRIMARY_WEBAPP@/soap
    wsdlEnabled=1

[@PRIMARY_ABLAPP@.@PRIMARY_WEBAPP@.REST]
    adapterEnabled=0

[@PRIMARY_ABLAPP@.@PRIMARY_WEBAPP@.WEB]
    adapterEnabled=1
    defaultCookieDomain=
    defaultCookiePath=
    defaultHandler=OpenEdge.Web.DefaultWebHandler
    srvrAppMode=production
    srvrDebug=0
    wsRoot=/@PRIMARY_WEBAPP@/static/webspeed
