<#
.SYNOPSIS
    Compares results of two k6 dashboard data files (as JSON) to analyze performance differences.

.DESCRIPTION
    Analyzes and compares HTTP response times, request rates, and other metrics
    between two k6 test runs to identify performance differences.
    
    This script expects dashboard-data.json files extracted from k6 HTML reports
    using Extract-K6Data.ps1. These files contain time-series metrics in NDJSON format.

.PARAMETER BaselineFile
    Path to the baseline dashboard-data.json file (e.g., Test A).
    This should be extracted using Extract-K6Data.ps1 from a k6 HTML report.

.PARAMETER ComparisonFile
    Path to the comparison dashboard-data.json file (e.g., Test B).
    This should be extracted using Extract-K6Data.ps1 from a k6 HTML report.

.PARAMETER OutputReport
    Optional path for saving the comparison report as a markdown file

.EXAMPLE
    .\Compare-K6Results.ps1 "test_a\dashboard-data.json" "test_b\dashboard-data.json"
    
.EXAMPLE
    .\Compare-K6Results.ps1 -BaselineFile "test_a-data.json" -ComparisonFile "test_b-data.json"

.EXAMPLE
    .\Compare-K6Results.ps1 -BaselineFile "test_a-data.json" -ComparisonFile "test_b-data.json" -OutputReport "comparison.md"
    
.NOTES
    Input files must be dashboard-data.json files extracted from k6 HTML reports.
    Use Extract-K6Data.ps1 to extract these files from the dashboard.html reports
    which are generated by k6 tests run with the -useDashboard option.
#>

param(
    [Parameter(Mandatory=$false)]
    [string]$BaselineFile,
    
    [Parameter(Mandatory=$false)]
    [string]$ComparisonFile,
    
    [Parameter(Mandatory=$false)]
    [string]$OutputReport
)

# Show usage if parameters missing
if (-not $BaselineFile -or -not $ComparisonFile) {
    Write-Host "`nk6 Results Comparison Tool" -ForegroundColor Cyan
    Write-Host "==========================`n" -ForegroundColor Cyan
    Write-Host "Compares dashboard-data.json files extracted from k6 HTML reports.`n" -ForegroundColor Gray
    Write-Host "USAGE:" -ForegroundColor Yellow
    Write-Host "  .\Compare-K6Results.ps1 `"<baseline-path>`" `"<comparison-path>`"`n"
    Write-Host "EXAMPLES:" -ForegroundColor Yellow
    Write-Host "  # Positional parameters (recommended)"
    Write-Host "  .\Compare-K6Results.ps1 `"test_a\dashboard-data.json`" `"test_b\dashboard-data.json`"`n"
    Write-Host "  # Named parameters"
    Write-Host "  .\Compare-K6Results.ps1 -BaselineFile `"test_a-data.json`" -ComparisonFile `"test_b-data.json`""
    Write-Host "  .\Compare-K6Results.ps1 -BaselineFile `"test_a-data.json`" -ComparisonFile `"test_b-data.json`" -OutputReport `"comparison.md`"`n"
    Write-Host "PARAMETERS:" -ForegroundColor Yellow
    Write-Host "  -BaselineFile    : Path to the baseline dashboard-data.json file (required)"
    Write-Host "  -ComparisonFile  : Path to the comparison dashboard-data.json file (required)"
    Write-Host "  -OutputReport    : Optional path for saving the report as a markdown file`n"
    Write-Host "NOTE:" -ForegroundColor Yellow
    Write-Host "  Use Extract-K6Data.ps1 to extract dashboard-data.json from k6 HTML reports.`n"
    exit 0
}

# Validate files exist
if (-not (Test-Path $BaselineFile -PathType Leaf)) {
    Write-Error "Baseline file not found: $BaselineFile"
    exit 1
}

if (-not (Test-Path $ComparisonFile -PathType Leaf)) {
    Write-Error "Comparison file not found: $ComparisonFile"
    exit 1
}

function Parse-K6Data {
    param([string]$FilePath)
    
    $lines = Get-Content $FilePath
    $data = @{
        Config = $null
        Params = $null
        Metrics = [ordered]@{}
        StartTime = $null
        Snapshots = @()
    }
    
    $inSnapshotPhase = $false
    $inTeardownPhase = $false
    
    foreach ($line in $lines) {
        $event = $line | ConvertFrom-Json
        
        switch ($event.event) {
            "config" { $data.Config = $event.data }
            "param" { $data.Params = $event.data }
            "metric" { 
                # Only collect metrics that appear before snapshots start
                # (setup/teardown metrics appear after snapshots and aren't in the arrays)
                if (-not $inSnapshotPhase) {
                    $event.data.PSObject.Properties | ForEach-Object {
                        if (-not $data.Metrics.Contains($_.Name)) {
                            $data.Metrics[$_.Name] = $_.Value
                        }
                    }
                } else {
                    # Second metric event means we've entered teardown phase
                    $inTeardownPhase = $true
                }
            }
            "start" { $data.StartTime = $event.data[0][0] }
            "snapshot" { 
                # Only collect snapshots from main test phase, not teardown
                if (-not $inTeardownPhase) {
                    $inSnapshotPhase = $true
                    $data.Snapshots += ,$event.data
                }
            }
        }
    }
    
    return $data
}

function Get-MetricStats {
    param(
        [array]$Snapshots,
        [System.Collections.Specialized.OrderedDictionary]$Metrics
    )
    
    # Build metric index mapping
    # The snapshot is an array where each element corresponds to one metric (in insertion order)
    # Each snapshot element is itself an array with values based on metric type
    $metricIndexMap = @{}
    $index = 0
    
    foreach ($entry in $Metrics.GetEnumerator()) {
        $metricIndexMap[$entry.Key] = $index
        $index++
    }
    
    # Validate that required metrics exist
    $requiredMetrics = @('http_req_duration', 'http_req_waiting', 'iteration_duration', 'http_reqs', 'http_req_failed', 'vus')
    foreach ($required in $requiredMetrics) {
        if (-not $metricIndexMap.ContainsKey($required)) {
            Write-Warning "Required metric '$required' not found in data. Results may be incomplete."
        }
    }
    
    # HARDCODED indices based on actual snapshot structure
    # These positions are verified against snapshot 1+ (after setup phase)
    # Note: Snapshot 0 has different structure with setup metrics populated
    $httpDurationIdx = 12
    $httpWaitingIdx = 22
    $iterationDurationIdx = 25
    $httpReqsIdx = 23  # Position 24 in setup snapshot, 23 in main test snapshots
    $httpFailedIdx = 14
    $vusIdx = 28
    
    $stats = @{
        Duration_Avg = @()
        Duration_P90 = @()
        Duration_P95 = @()
        Duration_P99 = @()
        Duration_Max = @()
        Duration_Min = @()
        Duration_Med = @()
        RequestRate = @()
        VUs = @()
        FailedRate = @()
        Waiting_Avg = @()
        Waiting_P95 = @()
        Iteration_Avg = @()
        Iteration_P95 = @()
    }
    
    foreach ($snapshot in $Snapshots) {
        # http_req_duration [avg, max, med, min, p90, p95, p99]
        if ($httpDurationIdx -ne $null -and $snapshot.Count -gt $httpDurationIdx -and $snapshot[$httpDurationIdx] -is [array] -and $snapshot[$httpDurationIdx].Count -ge 7) {
            $stats.Duration_Avg += [double]$snapshot[$httpDurationIdx][0]
            $stats.Duration_Max += [double]$snapshot[$httpDurationIdx][1]
            $stats.Duration_Med += [double]$snapshot[$httpDurationIdx][2]
            $stats.Duration_Min += [double]$snapshot[$httpDurationIdx][3]
            $stats.Duration_P90 += [double]$snapshot[$httpDurationIdx][4]
            $stats.Duration_P95 += [double]$snapshot[$httpDurationIdx][5]
            $stats.Duration_P99 += [double]$snapshot[$httpDurationIdx][6]
        }
        
        # http_req_waiting [avg, max, med, min, p90, p95, p99]
        if ($httpWaitingIdx -ne $null -and $snapshot.Count -gt $httpWaitingIdx -and $snapshot[$httpWaitingIdx] -is [array] -and $snapshot[$httpWaitingIdx].Count -ge 7) {
            $stats.Waiting_Avg += [double]$snapshot[$httpWaitingIdx][0]
            $stats.Waiting_P95 += [double]$snapshot[$httpWaitingIdx][5]
        }
        
        # iteration_duration [avg, max, med, min, p90, p95, p99]
        if ($iterationDurationIdx -ne $null -and $snapshot.Count -gt $iterationDurationIdx -and $snapshot[$iterationDurationIdx] -is [array] -and $snapshot[$iterationDurationIdx].Count -ge 7) {
            $stats.Iteration_Avg += [double]$snapshot[$iterationDurationIdx][0]
            $stats.Iteration_P95 += [double]$snapshot[$iterationDurationIdx][5]
        }
        
        # VUs - single value
        if ($vusIdx -ne $null -and $snapshot.Count -gt $vusIdx -and $snapshot[$vusIdx]) {
            $vu = if ($snapshot[$vusIdx] -is [array]) { $snapshot[$vusIdx][0] } else { $snapshot[$vusIdx] }
            $stats.VUs += [double]$vu
        }
        
        # Failed rate - single value
        if ($httpFailedIdx -ne $null -and $snapshot.Count -gt $httpFailedIdx -and $snapshot[$httpFailedIdx]) {
            $failed = if ($snapshot[$httpFailedIdx] -is [array]) { $snapshot[$httpFailedIdx][0] } else { $snapshot[$httpFailedIdx] }
            $stats.FailedRate += [double]$failed
        }
        
        # Request rate - from http_reqs [count, rate]
        if ($httpReqsIdx -ne $null -and $snapshot.Count -gt $httpReqsIdx -and $snapshot[$httpReqsIdx] -is [array] -and $snapshot[$httpReqsIdx].Count -gt 1) {
            $stats.RequestRate += [double]$snapshot[$httpReqsIdx][1]
        }
    }
    
    return $stats
}

function Calculate-Summary {
    param([array]$Values)
    
    if ($Values.Count -eq 0) {
        return @{
            Min = 0
            Max = 0
            Avg = 0
            Median = 0
            StdDev = 0
        }
    }
    
    $sorted = $Values | Sort-Object
    $avg = ($Values | Measure-Object -Average).Average
    $median = if ($sorted.Count % 2 -eq 0) {
        ($sorted[$sorted.Count/2 - 1] + $sorted[$sorted.Count/2]) / 2
    } else {
        $sorted[[math]::Floor($sorted.Count/2)]
    }
    
    $variance = ($Values | ForEach-Object { [math]::Pow($_ - $avg, 2) } | Measure-Object -Average).Average
    $stdDev = [math]::Sqrt($variance)
    
    return @{
        Min = ($sorted | Select-Object -First 1)
        Max = ($sorted | Select-Object -Last 1)
        Avg = $avg
        Median = $median
        StdDev = $stdDev
    }
}

# Load and parse both files
Write-Host "`n=== Loading Test Data ===" -ForegroundColor Cyan
Write-Host "Baseline: $BaselineFile"
Write-Host "Comparison: $ComparisonFile"

$baseline = Parse-K6Data -FilePath $BaselineFile
$comparison = Parse-K6Data -FilePath $ComparisonFile

Write-Host "`nBaseline event snapshots: $($baseline.Snapshots.Count)"
Write-Host "Comparison event snapshots: $($comparison.Snapshots.Count)"

# Extract metrics
Write-Host "`n=== Extracting Metrics ===" -ForegroundColor Cyan

Write-Host "Baseline metrics found: $($baseline.Metrics.Count)"
Write-Host "Comparison metrics found: $($comparison.Metrics.Count)"
if ($baseline.Snapshots.Count -gt 0) {
    Write-Host "Baseline snapshot array length: $($baseline.Snapshots[0].Count)"
}
if ($comparison.Snapshots.Count -gt 0) {
    Write-Host "Comparison snapshot array length: $($comparison.Snapshots[0].Count)"
}

$baselineStats = Get-MetricStats -Snapshots $baseline.Snapshots -Metrics $baseline.Metrics
$comparisonStats = Get-MetricStats -Snapshots $comparison.Snapshots -Metrics $comparison.Metrics

# Calculate summaries
Write-Host "`n=== HTTP REQUEST DURATION COMPARISON (milliseconds) ===" -ForegroundColor Yellow

$metrics = @("Duration_Avg", "Duration_P90", "Duration_P95", "Duration_P99", "Duration_Max")
$results = @()

foreach ($metric in $metrics) {
    $baseSummary = Calculate-Summary -Values $baselineStats[$metric]
    $compSummary = Calculate-Summary -Values $comparisonStats[$metric]
    
    $metricName = $metric -replace "Duration_", ""
    $diff = $compSummary.Avg - $baseSummary.Avg
    $diffPct = if ($baseSummary.Avg -gt 0) { ($diff / $baseSummary.Avg) * 100 } else { 0 }
    
    $result = [PSCustomObject]@{
        Metric = $metricName
        Baseline_Avg = [math]::Round($baseSummary.Avg, 2)
        Baseline_Min = [math]::Round($baseSummary.Min, 2)
        Baseline_Max = [math]::Round($baseSummary.Max, 2)
        Comparison_Avg = [math]::Round($compSummary.Avg, 2)
        Comparison_Min = [math]::Round($compSummary.Min, 2)
        Comparison_Max = [math]::Round($compSummary.Max, 2)
        Diff_ms = [math]::Round($diff, 2)
        Diff_Percent = [math]::Round($diffPct, 2)
    }
    
    $results += $result
}

$results | Format-Table -AutoSize

# Additional metrics
Write-Host "`n=== ADDITIONAL TIMING METRICS ===" -ForegroundColor Yellow

# Waiting time (Time to First Byte)
$baseWaiting = Calculate-Summary -Values $baselineStats.Waiting_Avg
$compWaiting = Calculate-Summary -Values $comparisonStats.Waiting_Avg
$waitingDiff = $compWaiting.Avg - $baseWaiting.Avg

Write-Host "`nHTTP Waiting Time (TTFB) - Average (ms):"
Write-Host "  Baseline    : $([math]::Round($baseWaiting.Avg, 2))"
Write-Host "  Comparison  : $([math]::Round($compWaiting.Avg, 2))"
$waitingSign = if ($waitingDiff -ge 0) { "+" } else { "" }
Write-Host "  Difference  : $waitingSign$([math]::Round($waitingDiff, 2))ms" -ForegroundColor $(if ($waitingDiff -gt 1000) { "Red" } elseif ($waitingDiff -gt 500) { "Yellow" } else { "Green" })

# Iteration duration
$baseIter = Calculate-Summary -Values $baselineStats.Iteration_Avg
$compIter = Calculate-Summary -Values $comparisonStats.Iteration_Avg
$iterDiff = $compIter.Avg - $baseIter.Avg

Write-Host "`nIteration Duration - Average (ms):"
Write-Host "  Baseline    : $([math]::Round($baseIter.Avg, 2))"
Write-Host "  Comparison  : $([math]::Round($compIter.Avg, 2))"
$iterSign = if ($iterDiff -ge 0) { "+" } else { "" }
Write-Host "  Difference  : $iterSign$([math]::Round($iterDiff, 2))ms" -ForegroundColor $(if ($iterDiff -gt 2000) { "Red" } elseif ($iterDiff -gt 1000) { "Yellow" } else { "Green" })

Write-Host "`n=== OTHER METRICS ===" -ForegroundColor Yellow

$otherMetrics = @{
    "Request Rate (req/s)" = @("RequestRate", $baselineStats.RequestRate, $comparisonStats.RequestRate)
    "Virtual Users" = @("VUs", $baselineStats.VUs, $comparisonStats.VUs)
}

foreach ($key in $otherMetrics.Keys) {
    $metric = $otherMetrics[$key]
    $baseSummary = Calculate-Summary -Values $metric[1]
    $compSummary = Calculate-Summary -Values $metric[2]
    
    Write-Host "`n$key"
    Write-Host "  Baseline    : Avg=$([math]::Round($baseSummary.Avg, 2)) Min=$([math]::Round($baseSummary.Min, 2)) Max=$([math]::Round($baseSummary.Max, 2))"
    Write-Host "  Comparison  : Avg=$([math]::Round($compSummary.Avg, 2)) Min=$([math]::Round($compSummary.Min, 2)) Max=$([math]::Round($compSummary.Max, 2))"
    
    $diff = $compSummary.Avg - $baseSummary.Avg
    $diffPct = if ($baseSummary.Avg -gt 0) { ($diff / $baseSummary.Avg) * 100 } else { 0 }
    $diffSign = if ($diff -ge 0) { "+" } else { "" }
    Write-Host "  Difference  : $diffSign$([math]::Round($diff, 2)) ($diffSign$([math]::Round($diffPct, 2))%)" -ForegroundColor $(if ($diff -lt 0) { "Green" } else { "Yellow" })
}

# Test duration comparison
Write-Host "`n=== TEST DURATION ===" -ForegroundColor Yellow
$baselineDuration = ($baseline.Snapshots.Count * 30) # event snapshots every 30 seconds
$comparisonDuration = ($comparison.Snapshots.Count * 30)
Write-Host "Baseline    : $([math]::Round($baselineDuration / 60, 1)) minutes ($($baseline.Snapshots.Count) event snapshots)"
Write-Host "Comparison  : $([math]::Round($comparisonDuration / 60, 1)) minutes ($($comparison.Snapshots.Count) event snapshots)"

# Key insights
Write-Host "`n=== KEY INSIGHTS ===" -ForegroundColor Cyan

$avgDurationDiff = ($results | Where-Object { $_.Metric -eq "Avg" }).Diff_ms
$avgDurationPct = ($results | Where-Object { $_.Metric -eq "Avg" }).Diff_Percent
$avgDurationSign = if ($avgDurationDiff -ge 0) { "+" } else { "" }
$avgDurationPctSign = if ($avgDurationPct -ge 0) { "+" } else { "" }
$p95Diff = ($results | Where-Object { $_.Metric -eq "P95" }).Diff_ms
$p95DiffSign = if ($p95Diff -ge 0) { "+" } else { "" }
$p99Diff = ($results | Where-Object { $_.Metric -eq "P99" }).Diff_ms
$p99DiffSign = if ($p99Diff -ge 0) { "+" } else { "" }

Write-Host "1. Average Response Time Impact:"
Write-Host "   Comparison adds ~$avgDurationSign$([math]::Round($avgDurationDiff, 2))ms ($avgDurationPctSign$([math]::Round($avgDurationPct, 1))%)" -ForegroundColor $(if ($avgDurationDiff -gt 1000) { "Red" } elseif ($avgDurationDiff -gt 500) { "Yellow" } else { "Green" })

Write-Host "`n2. P95 Latency Impact:"
Write-Host "   Comparison adds ~$p95DiffSign$([math]::Round($p95Diff, 2))ms at 95th percentile" -ForegroundColor $(if ($p95Diff -gt 2000) { "Red" } elseif ($p95Diff -gt 1000) { "Yellow" } else { "Green" })

Write-Host "`n3. P99 Latency Impact:"
Write-Host "   Comparison adds ~$p99DiffSign$([math]::Round($p99Diff, 2))ms at 99th percentile" -ForegroundColor $(if ($p99Diff -gt 3000) { "Red" } elseif ($p99Diff -gt 1500) { "Yellow" } else { "Green" })

$baseRequestRate = (Calculate-Summary -Values $baselineStats.RequestRate).Avg
$compRequestRate = (Calculate-Summary -Values $comparisonStats.RequestRate).Avg
$throughputImpact = if ($baseRequestRate -gt 0) { 
    (($baseRequestRate - $compRequestRate) / $baseRequestRate) * 100 
} else { 
    0 
}

Write-Host "`n4. Throughput Impact:"
if ($baseRequestRate -gt 0) {
    $throughputSign = if ($throughputImpact -ge 0) { "+" } else { "" }
    Write-Host "   Comparison reduces throughput by ~$throughputSign$([math]::Round($throughputImpact, 1))%" -ForegroundColor $(if ($throughputImpact -gt 50) { "Red" } elseif ($throughputImpact -gt 25) { "Yellow" } else { "Green" })
} else {
    Write-Host "   Unable to calculate throughput impact (baseline rate = 0)" -ForegroundColor Yellow
}

# Export markdown report if requested
if ($OutputReport) {
    $report = @()
    
    $report += "# k6 Results Comparison Report"
    $report += ""
    $report += "**Generated:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    $report += ""
    $report += "**Baseline:** ``$BaselineFile``"
    $report += ""
    $report += "**Comparison:** ``$ComparisonFile``"
    $report += ""
    $report += "- Baseline event snapshots: $($baseline.Snapshots.Count)"
    $report += "- Comparison event snapshots: $($comparison.Snapshots.Count)"
    $report += ""
    
    $report += "## HTTP Request Duration Comparison (milliseconds)"
    $report += ""
    
    # Create markdown table
    $report += "| Metric | Baseline Avg | Baseline Min | Baseline Max | Comparison Avg | Comparison Min | Comparison Max | Diff (ms) | Diff (%) |"
    $report += "|--------|--------------|--------------|--------------|----------------|----------------|----------------|-----------|----------|"
    foreach ($result in $results) {
        $report += "| $($result.Metric) | $($result.Baseline_Avg) | $($result.Baseline_Min) | $($result.Baseline_Max) | $($result.Comparison_Avg) | $($result.Comparison_Min) | $($result.Comparison_Max) | $($result.Diff_ms) | $($result.Diff_Percent) |"
    }
    $report += ""
    
    $report += "## Additional Timing Metrics"
    $report += ""
    
    $report += "### HTTP Waiting Time (TTFB) - Average (ms)"
    $report += ""
    $report += "- **Baseline:** $([math]::Round($baseWaiting.Avg, 2))"
    $report += "- **Comparison:** $([math]::Round($compWaiting.Avg, 2))"
    $waitingSign = if ($waitingDiff -ge 0) { "+" } else { "" }
    $report += "- **Difference:** $waitingSign$([math]::Round($waitingDiff, 2))ms"
    $report += ""
    
    $report += "### Iteration Duration - Average (ms)"
    $report += ""
    $report += "- **Baseline:** $([math]::Round($baseIter.Avg, 2))"
    $report += "- **Comparison:** $([math]::Round($compIter.Avg, 2))"
    $iterSign = if ($iterDiff -ge 0) { "+" } else { "" }
    $report += "- **Difference:** $iterSign$([math]::Round($iterDiff, 2))ms"
    $report += ""
    
    $report += "## Other Metrics"
    $report += ""
    
    foreach ($key in $otherMetrics.Keys) {
        $metric = $otherMetrics[$key]
        $baseSummary = Calculate-Summary -Values $metric[1]
        $compSummary = Calculate-Summary -Values $metric[2]
        
        $report += "### $key"
        $report += ""
        $report += "- **Baseline:** Avg=$([math]::Round($baseSummary.Avg, 2)) Min=$([math]::Round($baseSummary.Min, 2)) Max=$([math]::Round($baseSummary.Max, 2))"
        $report += "- **Comparison:** Avg=$([math]::Round($compSummary.Avg, 2)) Min=$([math]::Round($compSummary.Min, 2)) Max=$([math]::Round($compSummary.Max, 2))"
        
        $diff = $compSummary.Avg - $baseSummary.Avg
        $diffPct = if ($baseSummary.Avg -gt 0) { ($diff / $baseSummary.Avg) * 100 } else { 0 }
        $diffSign = if ($diff -ge 0) { "+" } else { "" }
        $report += "- **Difference:** $diffSign$([math]::Round($diff, 2)) ($diffSign$([math]::Round($diffPct, 2))%)"
        $report += ""
    }
    
    $report += "## Test Duration"
    $report += ""
    $report += "- **Baseline:** $([math]::Round($baselineDuration / 60, 1)) minutes ($($baseline.Snapshots.Count) event snapshots)"
    $report += "- **Comparison:** $([math]::Round($comparisonDuration / 60, 1)) minutes ($($comparison.Snapshots.Count) event snapshots)"
    $report += ""
    
    $report += "## Key Insights"
    $report += ""
    
    $report += "### 1. Average Response Time Impact"
    $report += ""
    $report += "Comparison adds ~$avgDurationSign$([math]::Round($avgDurationDiff, 2))ms ($avgDurationPctSign$([math]::Round($avgDurationPct, 1))%)"
    $report += ""
    
    $report += "### 2. P95 Latency Impact"
    $report += ""
    $report += "Comparison adds ~$p95DiffSign$([math]::Round($p95Diff, 2))ms at 95th percentile"
    $report += ""
    
    $report += "### 3. P99 Latency Impact"
    $report += ""
    $report += "Comparison adds ~$p99DiffSign$([math]::Round($p99Diff, 2))ms at 99th percentile"
    $report += ""
    
    $report += "### 4. Throughput Impact"
    $report += ""
    if ($baseRequestRate -gt 0) {
        $throughputSign = if ($throughputImpact -ge 0) { "+" } else { "" }
        $report += "Comparison reduces throughput by ~$throughputSign$([math]::Round($throughputImpact, 1))%"
    } else {
        $report += "Unable to calculate throughput impact (baseline rate = 0)"
    }
    
    $report | Out-File -FilePath $OutputReport -Encoding UTF8
    Write-Host "`n=== Report saved to: $OutputReport ===" -ForegroundColor Green
}

Write-Host ""
