/* ----------------------------------------------------------------------
 File : /Procedure/record/create/general.p
 Created : 11/10/2022 20:53:18.666+00:00
 Generated by DatabaseBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

using OpenEdge.Core.Assert.

/**
 * Creates a new Benefits record.
 *
 * @param inEmpNum The employee number (must be non-zero).
 * @throws Progress.Lang.Error If validation fails or transaction errors occur.
 */
procedure createBenefits :
   define input parameter inEmpNum as integer extent 0.

   Assert:NotZero(inEmpNum).

   do transaction:
        create Benefits.
        assign
            Benefits.EmpNum = inEmpNum
            .
   end. //transaction
end. //Benefits

/**
 * Creates a new BillTo record.
 *
 * @param inBillToID The billing address ID (must be non-zero).
 * @param inCustNum The customer number (must be non-zero).
 * @param inName The billing address name.
 * @throws Progress.Lang.Error If validation fails or transaction errors occur.
 */
procedure createBillTo :
   define input parameter inCustNum as integer extent 0.
   define input parameter inBillToID as integer extent 0.
   define input parameter inName as character extent 0.

   Assert:NotZero(inCustNum).
   Assert:NotZero(inBillToID).

   do transaction:
        create BillTo.
        assign
            BillTo.BillToID = inBillToID
            BillTo.CustNum = inCustNum
            BillTo.Name = inName
            .
   end. //transaction
end. //BillTo

procedure createBin :
   define input parameter inBinName as character extent 0.


   do transaction:
        create Bin.
        assign
            Bin.BinName = inBinName
            .
   end. //transaction
end. //Bin

procedure createCustomer :
   define input parameter inCustNum as integer extent 0.
   define input parameter inName as character extent 0.
   define input parameter inComments as character extent 0.


   do transaction:
        create Customer.
        assign
            Customer.Comments = inComments
            Customer.Name = inName
            .
   end. //transaction
end. //Customer

procedure createDepartment :
   define input parameter inDeptCode as character extent 0.
   define input parameter inDeptName as character extent 0.

   Assert:NotEqual(inDeptCode,'').

   do transaction:
        create Department.
        assign
            Department.DeptCode = inDeptCode
            Department.DeptName = inDeptName
            .
   end. //transaction
end. //Department

procedure createEmployee :
   define input parameter inFirstName as character extent 0.
   define input parameter inLastName as character extent 0.

   Assert:NotEqual(inFirstName,'').
   Assert:NotEqual(inLastName,'').

   do transaction:
        create Employee.
        assign
            Employee.FirstName = inFirstName
            Employee.LastName = inLastName
            .
   end. //transaction
end. //Employee

procedure createFamily :
   define input parameter inEmpNum as integer extent 0.
   define input parameter inRelativeName as character extent 0.

   Assert:NotZero(inEmpNum).
   Assert:NotEqual(inRelativeName,'').

   do transaction:
        create Family.
        assign
            Family.EmpNum = inEmpNum
            Family.RelativeName = inRelativeName
            .
   end. //transaction
end. //Family

procedure createFeedback :
   define input parameter inDepartment as character extent 0.
   define input parameter inComments as character extent 0.

   Assert:NotEqual(inDepartment,'').

   do transaction:
        create Feedback.
        assign
            Feedback.Department = inDepartment
            Feedback.Comments = inComments
            .
   end. //transaction
end. //Feedback

procedure createInventoryTrans :
   define input parameter inInvTransNum as integer extent 0.


   do transaction:
        create InventoryTrans.
        assign
            .
   end. //transaction
end. //InventoryTrans

procedure createInvoice :
   define input parameter inInvoiceNum as integer extent 0.
   define input parameter inAmount as decimal extent 0.


   do transaction:
        create Invoice.
        assign
            Invoice.Amount = inAmount
            .
   end. //transaction
end. //Invoice

procedure createItem :
   define input parameter inItemNum as integer extent 0.
   define input parameter inItemName as character extent 0.
   define input parameter inCatDescription as character extent 0.


   do transaction:
        create Item.
        assign
            Item.CatDescription = inCatDescription
            Item.ItemName = inItemName
            .
   end. //transaction
end. //Item

procedure createLocalDefault :
   define input parameter inLocalDefNum as integer extent 0.


   do transaction:
        create LocalDefault.
        assign
            .
   end. //transaction
end. //LocalDefault

procedure createOrder :
   define input parameter inOrderNum as integer extent 0.
   define input parameter inCustNum as integer extent 0.

   Assert:NotZero(inOrderNum).
   Assert:NotZero(inCustNum).

   do transaction:
        create Order.
        assign
            Order.CustNum = inCustNum
            .
   end. //transaction
end. //Order

procedure createOrderLine :
   define input parameter inLineNum as integer extent 0.
   define input parameter inOrderNum as integer extent 0.

   Assert:NotZero(inLineNum).
   Assert:NotZero(inOrderNum).

   do transaction:
        create OrderLine.
        assign
            OrderLine.LineNum = inLineNum
            OrderLine.OrderNum = inOrderNum
            .
   end. //transaction
end. //OrderLine

procedure createPOLine :
   define input parameter inLineNum as integer extent 0.
   define input parameter inPONum as integer extent 0.

   Assert:NotZero(inLineNum).
   Assert:NotZero(inPONum).

   do transaction:
        create POLine.
        assign
            POLine.LineNum = inLineNum
            POLine.PONum = inPONum
            .
   end. //transaction
end. //POLine

procedure createPurchaseOrder :
   define input parameter inPONum as integer extent 0.


   do transaction:
        create PurchaseOrder.
        assign
            .
   end. //transaction
end. //PurchaseOrder

procedure createRefCall :
   define input parameter inCallNum as integer extent 0.
   define input parameter inCustNum as integer extent 0.
   define input parameter inParent as character extent 0.

   Assert:NotZero(inCallNum).
   Assert:NotZero(inCustNum).
   Assert:NotEqual(inParent,'').

   do transaction:
        create RefCall.
        assign
            RefCall.CustNum = inCustNum
            RefCall.Parent = inParent
            .
   end. //transaction
end. //RefCall

procedure createSalesRep :
   define input parameter inSalesRep as character extent 0.
   define input parameter inRepName as character extent 0.

   Assert:NotEqual(inSalesRep,'').

   do transaction:
        create SalesRep.
        assign
            SalesRep.SalesRep = inSalesRep
            SalesRep.RepName = inRepName
            .
   end. //transaction
end. //SalesRep

procedure createShipTo :
   define input parameter inCustNum as integer extent 0.
   define input parameter inShipToID as integer extent 0.
   define input parameter inName as character extent 0.
   define input parameter inComments as character extent 0.

   Assert:NotZero(inCustNum).
   Assert:NotZero(inShipToID).

   do transaction:
        create ShipTo.
        assign
            ShipTo.CustNum = inCustNum
            ShipTo.ShipToID = inShipToID
            ShipTo.Comments = inComments
            ShipTo.Name = inName
            .
   end. //transaction
end. //ShipTo

procedure createState :
   define input parameter inState as character extent 0.
   define input parameter inStateName as character extent 0.

   Assert:NotEqual(inState,'').

   do transaction:
        create State.
        assign
            State.State = inState
            State.StateName = inStateName
            .
   end. //transaction
end. //State

procedure createSupplier :
   define input parameter inSupplierIDNum as integer extent 0.
   define input parameter inName as character extent 0.
   define input parameter inShipAmount as integer extent 0.
   define input parameter inComments as character extent 0.


   do transaction:
        create Supplier.
        assign
            Supplier.Comments = inComments
            Supplier.Name = inName
            Supplier.ShipAmount = inShipAmount
            .
   end. //transaction
end. //Supplier

procedure createSupplierItemXref :
   define input parameter inItemNum as integer extent 0.
   define input parameter inSupplierIDNum as integer extent 0.

   Assert:NotZero(inItemNum).
   Assert:NotZero(inSupplierIDNum).

   do transaction:
        create SupplierItemXref.
        assign
            SupplierItemXref.ItemNum = inItemNum
            SupplierItemXref.SupplierIDNum = inSupplierIDNum
            .
   end. //transaction
end. //SupplierItemXref

procedure createTimeSheet :
   define input parameter inDayRecorded as date extent 0.
   define input parameter inEmpNum as integer extent 0.

   Assert:NotNull(inDayRecorded).
   Assert:NotZero(inEmpNum).

   do transaction:
        create TimeSheet.
        assign
            TimeSheet.DayRecorded = inDayRecorded
            TimeSheet.EmpNum = inEmpNum
            .
   end. //transaction
end. //TimeSheet

procedure createVacation :
   define input parameter inEmpNum as integer extent 0.
   define input parameter inStartDate as date extent 0.

   Assert:NotZero(inEmpNum).
   Assert:NotNull(inStartDate).

   do transaction:
        create Vacation.
        assign
            Vacation.EmpNum = inEmpNum
            Vacation.StartDate = inStartDate
            .
   end. //transaction
end. //Vacation

procedure createWarehouse :
   define input parameter inWarehouseName as character extent 0.


   do transaction:
        create Warehouse.
        assign
            Warehouse.WarehouseName = inWarehouseName
            .
   end. //transaction
end. //Warehouse

