[@MONITOR_ABLAPP@]
    webApps=@MONITOR_WEBAPP@

[AppServer.Agent.@MONITOR_ABLAPP@]
    numInitialSessions=4
    PROPATH=${CATALINA_BASE}/ablapps/@MONITOR_ABLAPP@/openedge,${CATALINA_BASE}/openedge,${CATALINA_BASE}/ablapps/@PRIMARY_ABLAPP@/openedge/@CLASSPACKAGE@.apl,${DLC}/tty,${DLC}/tty/netlib/OpenEdge.Net.apl
    sessionStartupProc=@CLASSPATH@/Common/Util/SessionStartup.p
    sessionStartupProcParam={"dbName": "@DBNAME@", "dbPath": "CATALINA_BASE/db"}
    sessionActivateProc=@CLASSPATH@/Common/Util/SessionActivate.p

[AppServer.SessMgr.@MONITOR_ABLAPP@]
    agentLogEntryTypes=ASPlumbing,DB.Connects
    agentLogFile=${catalina.base}/logs/@MONITOR_ABLAPP@.agent.{yyyy-mm-dd}.log
    agentStartupParam=-T "${catalina.base}/temp" -pf "${catalina.base}/ablapps/@MONITOR_ABLAPP@/openedge/startup.pf"
    maxAgents=1
    minAgents=1
    numInitialAgents=1
    maxConnectionsPerAgent=4
    maxABLSessionsPerAgent=4

[@MONITOR_ABLAPP@.@MONITOR_WEBAPP@]
    allowRuntimeUpdates=1
    collectMetrics=3
    statusEnabled=1

[@MONITOR_ABLAPP@.@MONITOR_WEBAPP@.APSV]
    adapterEnabled=1
    enableRequestChunking=1
    oepingEnabled=1
    oepingProcedure=
    serviceFaultLevel=1
    useHTTPSessions=1

[@MONITOR_ABLAPP@.@MONITOR_WEBAPP@.SOAP]
    adapterEnabled=0
    adminEnabled=0
    adminSoapAction=urn:services-progress-com:wsa-admin:01
    debugClients=
    wsaUrl=http://${psc.as.host.name}:${psc.as.http.port}/@MONITOR_WEBAPP@/soap
    wsdlEnabled=1

[@MONITOR_ABLAPP@.@MONITOR_WEBAPP@.REST]
    adapterEnabled=0

[@MONITOR_ABLAPP@.@MONITOR_WEBAPP@.WEB]
    adapterEnabled=1
    defaultCookieDomain=
    defaultCookiePath=
    defaultHandler=OpenEdge.Web.DefaultWebHandler
    srvrAppMode=production
    srvrDebug=0
    wsRoot=/@MONITOR_WEBAPP@/static/webspeed
