/* ----------------------------------------------------------------------
 File : /Function/record/delete/general.p
 Created : 11/10/2022 20:53:18.693+00:00
 Generated by DatabaseBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

using OpenEdge.Core.Assert.

function deleteBenefits returns logical (input inEmpNum as integer):
   Assert:NotZero(inEmpNum).
   find first Benefits exclusive-lock
      where Benefits.EmpNum = inEmpNum
      no-error.
   Assert:IsTrue(available Benefits).
   do transaction:

      delete Benefits.
   end.
end. //Benefits

function deleteBillTo returns logical (input inCustNum as integer,input inBillToID as integer):
   Assert:NotZero(inBillToID).
   Assert:NotZero(inCustNum).
   find first BillTo exclusive-lock
      where BillTo.BillToID = inBillToID
      and   BillTo.CustNum = inCustNum
      no-error.
   Assert:IsTrue(available BillTo).
   do transaction:

      delete BillTo.
   end.
end. //BillTo

function deleteBin returns logical (input inBinNum as integer,input inBinName as character):
   Assert:NotZero(inBinNum).
   find first Bin exclusive-lock
      where Bin.BinNum = inBinNum
      no-error.
   Assert:IsTrue(available Bin).
   do transaction:

      delete Bin.
   end.
end. //Bin

function deleteCustomer returns logical (input inCustNum as integer):
   Assert:NotZero(inCustNum).
   find first Customer exclusive-lock
      where Customer.CustNum = inCustNum
      no-error.
   Assert:IsTrue(available Customer).
   do transaction:

      delete Customer.
   end.
end. //Customer

function deleteDepartment returns logical (input inDeptCode as character,input inDeptName as character):
   Assert:NotNullOrEmpty(inDeptCode).
   find first Department exclusive-lock
      where Department.DeptCode = inDeptCode
      no-error.
   Assert:IsTrue(available Department).
   do transaction:

      delete Department.
   end.
end. //Department

function deleteEmployee returns logical (input inEmpNum as integer,input inFirstName as character,input inLastName as character):
   Assert:NotZero(inEmpNum).
   Assert:NotNullOrEmpty(inFirstName).
   Assert:NotNullOrEmpty(inLastName).
   find first Employee exclusive-lock
      where Employee.EmpNum = inEmpNum
      and   Employee.FirstName = inFirstName
      and   Employee.LastName = inLastName
      no-error.
   Assert:IsTrue(available Employee).
   do transaction:

      delete Employee.
   end.
end. //Employee

function deleteFamily returns logical (input inEmpNum as integer,input inRelativeName as character):
   Assert:NotZero(inEmpNum).
   Assert:NotNullOrEmpty(inRelativeName).
   find first Family exclusive-lock
      where Family.EmpNum = inEmpNum
      and   Family.RelativeName = inRelativeName
      no-error.
   Assert:IsTrue(available Family).
   do transaction:

      delete Family.
   end.
end. //Family

function deleteFeedback returns logical (input inDepartment as character,input inComments as character):
   Assert:NotNullOrEmpty(inDepartment).
   find first Feedback exclusive-lock
      where Feedback.Department = inDepartment
      no-error.
   Assert:IsTrue(available Feedback).
   do transaction:

      delete Feedback.
   end.
end. //Feedback

function deleteInventoryTrans returns logical (input inInvTransNum as integer):
   Assert:NotZero(inInvTransNum).
   find first InventoryTrans exclusive-lock
      where InventoryTrans.InvTransNum = inInvTransNum
      no-error.
   Assert:IsTrue(available InventoryTrans).
   do transaction:

      delete InventoryTrans.
   end.
end. //InventoryTrans

function deleteInvoice returns logical (input inInvoiceNum as integer,input inAmount as decimal):
   Assert:NotZero(inInvoiceNum).
   find first Invoice exclusive-lock
      where Invoice.InvoiceNum = inInvoiceNum
      no-error.
   Assert:IsTrue(available Invoice).
   do transaction:

      delete Invoice.
   end.
end. //Invoice

function deleteItem returns logical (input inItemNum as integer):
   Assert:NotZero(inItemNum).
   find first Item exclusive-lock
      where Item.ItemNum = inItemNum
      no-error.
   Assert:IsTrue(available Item).
   do transaction:

      delete Item.
   end.
end. //Item

function deleteLocalDefault returns logical (input inLocalDefNum as integer):
   Assert:NotZero(inLocalDefNum).
   find first LocalDefault exclusive-lock
      where LocalDefault.LocalDefNum = inLocalDefNum
      no-error.
   Assert:IsTrue(available LocalDefault).
   do transaction:

      delete LocalDefault.
   end.
end. //LocalDefault

function deleteOrder returns logical (input inOrderNum as integer):
   Assert:NotZero(inOrderNum).
   find first Order exclusive-lock
      where Order.OrderNum = inOrderNum
      no-error.
   Assert:IsTrue(available Order).
   do transaction:

      delete Order.
   end.
end. //Order

function deleteOrderLine returns logical (input inOrderNum as integer,input inLineNum as integer):
   Assert:NotZero(inLineNum).
   Assert:NotZero(inOrderNum).
   find first OrderLine exclusive-lock
      where OrderLine.OrderNum = inOrderNum
      and   OrderLine.LineNum = inLineNum
      no-error.
   Assert:IsTrue(available OrderLine).
   do transaction:

      delete OrderLine.
   end.
end. //OrderLine

function deletePOLine returns logical (input inLineNum as integer,input inPONum as integer):
   Assert:NotZero(inLineNum).
   Assert:NotZero(inPONum).
   find first POLine exclusive-lock
      where POLine.LineNum = inLineNum
      and   POLine.PONum = inPONum
      no-error.
   Assert:IsTrue(available POLine).
   do transaction:

      delete POLine.
   end.
end. //POLine

function deletePurchaseOrder returns logical (input inPONum as integer):
   Assert:NotZero(inPONum).
   find first PurchaseOrder exclusive-lock
      where PurchaseOrder.PONum = inPONum
      no-error.
   Assert:IsTrue(available PurchaseOrder).
   do transaction:

      delete PurchaseOrder.
   end.
end. //PurchaseOrder

function deleteRefCall returns logical (input inCallNum as integer):
   Assert:NotZero(inCallNum).
   find first RefCall exclusive-lock
      where RefCall.CallNum = inCallNum
      no-error.
   Assert:IsTrue(available RefCall).
   do transaction:

      delete RefCall.
   end.
end. //RefCall

function deleteSalesRep returns logical (input inSalesRep as character,input inRepName as character):
   Assert:NotNullOrEmpty(inSalesRep).
   find first SalesRep exclusive-lock
      where SalesRep.SalesRep = inSalesRep
      no-error.
   Assert:IsTrue(available SalesRep).
   do transaction:

      delete SalesRep.
   end.
end. //SalesRep

function deleteShipTo returns logical (input inCustNum as integer,input inShipToID as integer):
   Assert:NotZero(inCustNum).
   Assert:NotZero(inShipToID).
   find first ShipTo exclusive-lock
      where ShipTo.CustNum = inCustNum
      and   ShipTo.ShipToID = inShipToID
      no-error.
   Assert:IsTrue(available ShipTo).
   do transaction:

      delete ShipTo.
   end.
end. //ShipTo

function deleteState returns logical (input inState as character,input inStateName as character):
   Assert:NotNullOrEmpty(inState).
   find first State exclusive-lock
      where State.State = inState
      no-error.
   Assert:IsTrue(available State).
   do transaction:

      delete State.
   end.
end. //State

function deleteSupplier returns logical (input inSupplierIDNum as integer):
   Assert:NotZero(inSupplierIDNum).
   find first Supplier exclusive-lock
      where Supplier.SupplierIDNum = inSupplierIDNum
      no-error.
   Assert:IsTrue(available Supplier).
   do transaction:

      delete Supplier.
   end.
end. //Supplier

function deleteSupplierItemXref returns logical (input inSupplierIDNum as integer,input inItemNum as integer):
   Assert:NotZero(inItemNum).
   Assert:NotZero(inSupplierIDNum).
   find first SupplierItemXref exclusive-lock
      where SupplierItemXref.ItemNum = inItemNum
      and   SupplierItemXref.SupplierIDNum = inSupplierIDNum
      no-error.
   Assert:IsTrue(available SupplierItemXref).
   do transaction:

      delete SupplierItemXref.
   end.
end. //SupplierItemXref

function deleteTimeSheet returns logical (input inDayRecorded as date,input inEmpNum as integer):
   Assert:NotNull(inDayRecorded).
   Assert:NotZero(inEmpNum).
   find first TimeSheet exclusive-lock
      where TimeSheet.DayRecorded = inDayRecorded
      and   TimeSheet.EmpNum = inEmpNum
      no-error.
   Assert:IsTrue(available TimeSheet).
   do transaction:

      delete TimeSheet.
   end.
end. //TimeSheet

function deleteVacation returns logical (input inEmpNum as integer,input inStartDate as date):
   Assert:NotZero(inEmpNum).
   Assert:NotNull(inStartDate).
   find first Vacation exclusive-lock
      where Vacation.EmpNum = inEmpNum
      and   Vacation.StartDate = inStartDate
      no-error.
   Assert:IsTrue(available Vacation).
   do transaction:

      delete Vacation.
   end.
end. //Vacation

function deleteWarehouse returns logical (input inWarehouseNum as integer,input inWarehouseName as character):
   Assert:NotZero(inWarehouseNum).
   find first Warehouse exclusive-lock
      where Warehouse.WarehouseNum = inWarehouseNum
      no-error.
   Assert:IsTrue(available Warehouse).
   do transaction:

      delete Warehouse.
   end.
end. //Warehouse

