/* ----------------------------------------------------------------------
 File : /Procedure/record/delete/general.p
 Created : 11/10/2022 20:53:18.687+00:00
 Generated by DatabaseBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

using OpenEdge.Core.Assert.

procedure deleteBenefits :
   define input parameter inEmpNum as integer extent 0.

   Assert:NotZero(inEmpNum).
   find first Benefits exclusive-lock
      where Benefits.EmpNum = inEmpNum
      no-error.
   Assert:IsTrue(available Benefits).
   do transaction:

      delete Benefits.
   end.
end. //Benefits

procedure deleteBillTo :
   define input parameter inCustNum as integer extent 0.
   define input parameter inBillToID as integer extent 0.

   Assert:NotZero(inCustNum).
   Assert:NotZero(inBillToID).
   find first BillTo exclusive-lock
      where BillTo.BillToID = inBillToID
      and   BillTo.CustNum = inCustNum
      no-error.
   Assert:IsTrue(available BillTo).
   do transaction:

      delete BillTo.
   end.
end. //BillTo

procedure deleteBin :
   define input parameter inBinNum as integer extent 0.
   define input parameter inBinName as character extent 0.

   Assert:NotZero(inBinNum).
   find first Bin exclusive-lock
      where Bin.BinNum = inBinNum
      no-error.
   Assert:IsTrue(available Bin).
   do transaction:

      delete Bin.
   end.
end. //Bin

procedure deleteCustomer :
   define input parameter inCustNum as integer extent 0.

   Assert:NotZero(inCustNum).
   find first Customer exclusive-lock
      where Customer.CustNum = inCustNum
      no-error.
   Assert:IsTrue(available Customer).
   do transaction:

      delete Customer.
   end.
end. //Customer

procedure deleteDepartment :
   define input parameter inDeptCode as character extent 0.
   define input parameter inDeptName as character extent 0.

   Assert:NotEqual(inDeptCode,'').
   find first Department exclusive-lock
      where Department.DeptCode = inDeptCode
      no-error.
   Assert:IsTrue(available Department).
   do transaction:

      delete Department.
   end.
end. //Department

procedure deleteEmployee :
   define input parameter inEmpNum as integer extent 0.
   define input parameter inFirstName as character extent 0.
   define input parameter inLastName as character extent 0.

   Assert:NotZero(inEmpNum).
   Assert:NotEqual(inFirstName,'').
   Assert:NotEqual(inLastName,'').
   find first Employee exclusive-lock
      where Employee.EmpNum = inEmpNum
      and   Employee.FirstName = inFirstName
      and   Employee.LastName = inLastName
      no-error.
   Assert:IsTrue(available Employee).
   do transaction:

      delete Employee.
   end.
end. //Employee

procedure deleteFamily :
   define input parameter inEmpNum as integer extent 0.
   define input parameter inRelativeName as character extent 0.

   Assert:NotZero(inEmpNum).
   Assert:NotEqual(inRelativeName,'').
   find first Family exclusive-lock
      where Family.EmpNum = inEmpNum
      and   Family.RelativeName = inRelativeName
      no-error.
   Assert:IsTrue(available Family).
   do transaction:

      delete Family.
   end.
end. //Family

procedure deleteFeedback :
   define input parameter inDepartment as character extent 0.
   define input parameter inComments as character extent 0.

   Assert:NotEqual(inDepartment,'').
   find first Feedback exclusive-lock
      where Feedback.Department = inDepartment
      no-error.
   Assert:IsTrue(available Feedback).
   do transaction:

      delete Feedback.
   end.
end. //Feedback

procedure deleteInventoryTrans :
   define input parameter inInvTransNum as integer extent 0.

   Assert:NotZero(inInvTransNum).
   find first InventoryTrans exclusive-lock
      where InventoryTrans.InvTransNum = inInvTransNum
      no-error.
   Assert:IsTrue(available InventoryTrans).
   do transaction:

      delete InventoryTrans.
   end.
end. //InventoryTrans

procedure deleteInvoice :
   define input parameter inInvoiceNum as integer extent 0.
   define input parameter inAmount as decimal extent 0.

   Assert:NotZero(inInvoiceNum).
   find first Invoice exclusive-lock
      where Invoice.InvoiceNum = inInvoiceNum
      no-error.
   Assert:IsTrue(available Invoice).
   do transaction:

      delete Invoice.
   end.
end. //Invoice

procedure deleteItem :
   define input parameter inItemNum as integer extent 0.

   Assert:NotZero(inItemNum).
   find first Item exclusive-lock
      where Item.ItemNum = inItemNum
      no-error.
   Assert:IsTrue(available Item).
   do transaction:

      delete Item.
   end.
end. //Item

procedure deleteLocalDefault :
   define input parameter inLocalDefNum as integer extent 0.

   Assert:NotZero(inLocalDefNum).
   find first LocalDefault exclusive-lock
      where LocalDefault.LocalDefNum = inLocalDefNum
      no-error.
   Assert:IsTrue(available LocalDefault).
   do transaction:

      delete LocalDefault.
   end.
end. //LocalDefault

procedure deleteOrder :
   define input parameter inOrderNum as integer extent 0.

   Assert:NotZero(inOrderNum).
   find first Order exclusive-lock
      where Order.OrderNum = inOrderNum
      no-error.
   Assert:IsTrue(available Order).
   do transaction:

      delete Order.
   end.
end. //Order

procedure deleteOrderLine :
   define input parameter inOrderNum as integer extent 0.
   define input parameter inLineNum as integer extent 0.

   Assert:NotZero(inOrderNum).
   Assert:NotZero(inLineNum).
   find first OrderLine exclusive-lock
      where OrderLine.OrderNum = inOrderNum
      and   OrderLine.LineNum = inLineNum
      no-error.
   Assert:IsTrue(available OrderLine).
   do transaction:

      delete OrderLine.
   end.
end. //OrderLine

procedure deletePOLine :
   define input parameter inLineNum as integer extent 0.
   define input parameter inPONum as integer extent 0.

   Assert:NotZero(inLineNum).
   Assert:NotZero(inPONum).
   find first POLine exclusive-lock
      where POLine.LineNum = inLineNum
      and   POLine.PONum = inPONum
      no-error.
   Assert:IsTrue(available POLine).
   do transaction:

      delete POLine.
   end.
end. //POLine

procedure deletePurchaseOrder :
   define input parameter inPONum as integer extent 0.

   Assert:NotZero(inPONum).
   find first PurchaseOrder exclusive-lock
      where PurchaseOrder.PONum = inPONum
      no-error.
   Assert:IsTrue(available PurchaseOrder).
   do transaction:

      delete PurchaseOrder.
   end.
end. //PurchaseOrder

procedure deleteRefCall :
   define input parameter inCallNum as integer extent 0.

   Assert:NotZero(inCallNum).
   find first RefCall exclusive-lock
      where RefCall.CallNum = inCallNum
      no-error.
   Assert:IsTrue(available RefCall).
   do transaction:

      delete RefCall.
   end.
end. //RefCall

procedure deleteSalesRep :
   define input parameter inSalesRep as character extent 0.
   define input parameter inRepName as character extent 0.

   Assert:NotEqual(inSalesRep,'').
   find first SalesRep exclusive-lock
      where SalesRep.SalesRep = inSalesRep
      no-error.
   Assert:IsTrue(available SalesRep).
   do transaction:

      delete SalesRep.
   end.
end. //SalesRep

procedure deleteShipTo :
   define input parameter inCustNum as integer extent 0.
   define input parameter inShipToID as integer extent 0.

   Assert:NotZero(inCustNum).
   Assert:NotZero(inShipToID).
   find first ShipTo exclusive-lock
      where ShipTo.CustNum = inCustNum
      and   ShipTo.ShipToID = inShipToID
      no-error.
   Assert:IsTrue(available ShipTo).
   do transaction:

      delete ShipTo.
   end.
end. //ShipTo

procedure deleteState :
   define input parameter inState as character extent 0.
   define input parameter inStateName as character extent 0.

   Assert:NotEqual(inState,'').
   find first State exclusive-lock
      where State.State = inState
      no-error.
   Assert:IsTrue(available State).
   do transaction:

      delete State.
   end.
end. //State

procedure deleteSupplier :
   define input parameter inSupplierIDNum as integer extent 0.

   Assert:NotZero(inSupplierIDNum).
   find first Supplier exclusive-lock
      where Supplier.SupplierIDNum = inSupplierIDNum
      no-error.
   Assert:IsTrue(available Supplier).
   do transaction:

      delete Supplier.
   end.
end. //Supplier

procedure deleteSupplierItemXref :
   define input parameter inSupplierIDNum as integer extent 0.
   define input parameter inItemNum as integer extent 0.

   Assert:NotZero(inSupplierIDNum).
   Assert:NotZero(inItemNum).
   find first SupplierItemXref exclusive-lock
      where SupplierItemXref.ItemNum = inItemNum
      and   SupplierItemXref.SupplierIDNum = inSupplierIDNum
      no-error.
   Assert:IsTrue(available SupplierItemXref).
   do transaction:

      delete SupplierItemXref.
   end.
end. //SupplierItemXref

procedure deleteTimeSheet :
   define input parameter inDayRecorded as date extent 0.
   define input parameter inEmpNum as integer extent 0.

   Assert:NotNull(inDayRecorded).
   Assert:NotZero(inEmpNum).
   find first TimeSheet exclusive-lock
      where TimeSheet.DayRecorded = inDayRecorded
      and   TimeSheet.EmpNum = inEmpNum
      no-error.
   Assert:IsTrue(available TimeSheet).
   do transaction:

      delete TimeSheet.
   end.
end. //TimeSheet

procedure deleteVacation :
   define input parameter inEmpNum as integer extent 0.
   define input parameter inStartDate as date extent 0.

   Assert:NotZero(inEmpNum).
   Assert:NotNull(inStartDate).
   find first Vacation exclusive-lock
      where Vacation.EmpNum = inEmpNum
      and   Vacation.StartDate = inStartDate
      no-error.
   Assert:IsTrue(available Vacation).
   do transaction:

      delete Vacation.
   end.
end. //Vacation

procedure deleteWarehouse :
   define input parameter inWarehouseNum as integer extent 0.
   define input parameter inWarehouseName as character extent 0.

   Assert:NotZero(inWarehouseNum).
   find first Warehouse exclusive-lock
      where Warehouse.WarehouseNum = inWarehouseNum
      no-error.
   Assert:IsTrue(available Warehouse).
   do transaction:

      delete Warehouse.
   end.
end. //Warehouse

