
FUNCTION division RETURNS DECIMAL( INPUT iNum1 AS DECIMAL, INPUT iNum2 AS DECIMAL) {1}:
FUNCTION addition RETURNS DECIMAL( INPUT iNum1 AS DECIMAL, INPUT iNum2 AS DECIMAL) {1} :
FUNCTION subtraction RETURNS DECIMAL( INPUT iNum1 AS DECIMAL, INPUT iNum2 AS DECIMAL) {1}:
FUNCTION multiplication RETURNS DECIMAL( INPUT iNum1 AS DECIMAL, INPUT iNum2 AS DECIMAL) {1}:   
FUNCTION GetSize RETURNS INT64() {1}:
FUNCTION GetData RETURNS LONGCHAR() {1}:
FUNCTION WhatLetter RETURNS CHARACTER(INPUT iLoc AS INTEGER) {1}:
FUNCTION WhatWord RETURNS CHARACTER(INPUT iStart AS INTEGER, INPUT iLength AS INTEGER) {1}:
FUNCTION FindIn RETURNS INTEGER(INPUT iLetter AS CHARACTER) {1}:
FUNCTION HelloJoin RETURNS CHARACTER(INPUT iWord AS CHARACTER) {1}:
FUNCTION AddRecords RETURNS INT64(INPUT iNumToCreate AS INT64) {1}:
FUNCTION CreateDynamic RETURNS LOGICAL(INPUT iNumFields AS INTEGER) {1}:
FUNCTION CreateStatic RETURNS LOGICAL(INPUT kTableName AS CHARACTER) {1}:
FUNCTION DeleteTable RETURNS LOGICAL() {1}: