/* ----------------------------------------------------------------------
 File    : OpenEdge/LoadSuite/Common/include/RecordForward.i
 Created : 11/10/2022 20:53:18.666+00:00
 Generated by DatabaseBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

function createBenefits returns logical (input inEmpNum as int64 extent 0) {1}:
function createBillTo returns logical (input inBillToID as int64 extent 0,input inCustNum as int64 extent 0,input inName as character extent 0) {1}:
function createBin returns logical (input inBinNum as int64 extent 0,input inBinName as character extent 0) {1}:
function createCustomer returns logical (input inCustNum as int64 extent 0,input inComments as character extent 0,input inName as character extent 0) {1}:
function createDepartment returns logical (input inDeptCode as character extent 0,input inDeptName as character extent 0) {1}:
function createEmployee returns logical (input inEmpNum as int64 extent 0,input inFirstName as character extent 0,input inLastName as character extent 0) {1}:
function createFamily returns logical (input inEmpNum as int64 extent 0,input inRelativeName as character extent 0) {1}:
function createFeedback returns logical (input inDepartment as character extent 0,input inComments as character extent 0) {1}:
function createInventoryTrans returns logical (input inInvTransNum as int64 extent 0) {1}:
function createInvoice returns logical (input inInvoiceNum as int64 extent 0,input inAmount as decimal extent 0) {1}:
function createItem returns logical (input inItemNum as int64 extent 0,input inCatDescription as character extent 0,input inItemName as character extent 0) {1}:
function createLocalDefault returns logical (input inLocalDefNum as int64 extent 0) {1}:
function createOrder returns logical (input inCustNum as int64 extent 0,input inOrderNum as int64 extent 0) {1}:
function createOrderLine returns logical (input inLineNum as int64 extent 0,input inOrderNum as int64 extent 0) {1}:
function createPOLine returns logical (input inLineNum as int64 extent 0,input inPONum as int64 extent 0) {1}:
function createPurchaseOrder returns logical (input inPONum as int64 extent 0) {1}:
function createRefCall returns logical (input inCallNum as integer extent 0,input inCustNum as int64 extent 0,input inParent as character extent 0) {1}:
function createSalesRep returns logical (input inSalesRep as character extent 0,input inRepName as character extent 0) {1}:
function createShipTo returns logical (input inCustNum as int64 extent 0,input inShipToID as int64 extent 0,input inComments as character extent 0,input inName as character extent 0) {1}:
function createState returns logical (input inState as character extent 0,input inStateName as character extent 0) {1}:
function createSupplier returns logical (input inSupplierIDNum as int64 extent 0,input inComments as character extent 0,input inName as character extent 0,input inShipAmount as int64 extent 0) {1}:
function createSupplierItemXref returns logical (input inItemNum as int64 extent 0,input inSupplierIDNum as int64 extent 0) {1}:
function createTimeSheet returns logical (input inDayRecorded as date extent 0,input inEmpNum as int64 extent 0) {1}:
function createVacation returns logical (input inEmpNum as int64 extent 0,input inStartDate as date extent 0) {1}:
function createWarehouse returns logical (input inWarehouseNum as int64 extent 0,input inWarehouseName as character extent 0) {1}:
function updateBenefits returns logical (input inEmpNum as int64 extent 0) {1}:
function updateBillTo returns logical (input inBillToID as int64 extent 0,input inCustNum as int64 extent 0,input inName as character extent 0) {1}:
function updateBin returns logical (input inBinNum as int64 extent 0,input inBinName as character extent 0) {1}:
function updateCustomer returns logical (input inCustNum as int64 extent 0,input inComments as character extent 0,input inName as character extent 0) {1}:
function updateDepartment returns logical (input inDeptCode as character extent 0,input inDeptName as character extent 0) {1}:
function updateEmployee returns logical (input inEmpNum as int64 extent 0,input inFirstName as character extent 0,input inLastName as character extent 0) {1}:
function updateFamily returns logical (input inEmpNum as int64 extent 0,input inRelativeName as character extent 0) {1}:
function updateFeedback returns logical (input inDepartment as character extent 0,input inComments as character extent 0) {1}:
function updateInventoryTrans returns logical (input inInvTransNum as int64 extent 0) {1}:
function updateInvoice returns logical (input inInvoiceNum as int64 extent 0,input inAmount as decimal extent 0) {1}:
function updateItem returns logical (input inItemNum as int64 extent 0,input inCatDescription as character extent 0,input inItemName as character extent 0) {1}:
function updateLocalDefault returns logical (input inLocalDefNum as int64 extent 0) {1}:
function updateOrder returns logical (input inCustNum as int64 extent 0,input inOrderNum as int64 extent 0) {1}:
function updateOrderLine returns logical (input inLineNum as int64 extent 0,input inOrderNum as int64 extent 0) {1}:
function updatePOLine returns logical (input inLineNum as int64 extent 0,input inPONum as int64 extent 0) {1}:
function updatePurchaseOrder returns logical (input inPONum as int64 extent 0) {1}:
function updateRefCall returns logical (input inCallNum as integer extent 0,input inCustNum as int64 extent 0,input inParent as character extent 0) {1}:
function updateSalesRep returns logical (input inSalesRep as character extent 0,input inRepName as character extent 0) {1}:
function updateShipTo returns logical (input inCustNum as int64 extent 0,input inShipToID as int64 extent 0,input inComments as character extent 0,input inName as character extent 0) {1}:
function updateState returns logical (input inState as character extent 0,input inStateName as character extent 0) {1}:
function updateSupplier returns logical (input inSupplierIDNum as int64 extent 0,input inComments as character extent 0,input inName as character extent 0,input inShipAmount as int64 extent 0) {1}:
function updateSupplierItemXref returns logical (input inItemNum as int64 extent 0,input inSupplierIDNum as int64 extent 0) {1}:
function updateTimeSheet returns logical (input inDayRecorded as date extent 0,input inEmpNum as int64 extent 0) {1}:
function updateVacation returns logical (input inEmpNum as int64 extent 0,input inStartDate as date extent 0) {1}:
function updateWarehouse returns logical (input inWarehouseNum as int64 extent 0,input inWarehouseName as character extent 0) {1}:
function deleteBenefits returns logical (input inEmpNum as int64 extent 0) {1}:
function deleteBillTo returns logical (input inBillToID as int64 extent 0,input inCustNum as int64 extent 0,input inName as character extent 0) {1}:
function deleteBin returns logical (input inBinNum as int64 extent 0,input inBinName as character extent 0) {1}:
function deleteCustomer returns logical (input inCustNum as int64 extent 0,input inComments as character extent 0,input inName as character extent 0) {1}:
function deleteDepartment returns logical (input inDeptCode as character extent 0,input inDeptName as character extent 0) {1}:
function deleteEmployee returns logical (input inEmpNum as int64 extent 0,input inFirstName as character extent 0,input inLastName as character extent 0) {1}:
function deleteFamily returns logical (input inEmpNum as int64 extent 0,input inRelativeName as character extent 0) {1}:
function deleteFeedback returns logical (input inDepartment as character extent 0,input inComments as character extent 0) {1}:
function deleteInventoryTrans returns logical (input inInvTransNum as int64 extent 0) {1}:
function deleteInvoice returns logical (input inInvoiceNum as int64 extent 0,input inAmount as decimal extent 0) {1}:
function deleteItem returns logical (input inItemNum as int64 extent 0,input inCatDescription as character extent 0,input inItemName as character extent 0) {1}:
function deleteLocalDefault returns logical (input inLocalDefNum as int64 extent 0) {1}:
function deleteOrder returns logical (input inCustNum as int64 extent 0,input inOrderNum as int64 extent 0) {1}:
function deleteOrderLine returns logical (input inOrderNum as int64 extent 0,input inLineNum as int64 extent 0) {1}:
function deletePOLine returns logical (input inLineNum as int64 extent 0,input inPONum as int64 extent 0) {1}:
function deletePurchaseOrder returns logical (input inPONum as int64 extent 0) {1}:
function deleteRefCall returns logical (input inCallNum as integer extent 0,input inCustNum as int64 extent 0,input inParent as character extent 0) {1}:
function deleteSalesRep returns logical (input inSalesRep as character extent 0,input inRepName as character extent 0) {1}:
function deleteShipTo returns logical (input inCustNum as int64 extent 0,input inShipToID as int64 extent 0,input inComments as character extent 0,input inName as character extent 0) {1}:
function deleteState returns logical (input inState as character extent 0,input inStateName as character extent 0) {1}:
function deleteSupplier returns logical (input inSupplierIDNum as int64 extent 0,input inComments as character extent 0,input inName as character extent 0,input inShipAmount as int64 extent 0) {1}:
function deleteSupplierItemXref returns logical (input inItemNum as int64 extent 0,input inSupplierIDNum as int64 extent 0) {1}:
function deleteTimeSheet returns logical (input inDayRecorded as date extent 0,input inEmpNum as int64 extent 0) {1}:
function deleteVacation returns logical (input inEmpNum as int64 extent 0,input inStartDate as date extent 0) {1}:
function deleteWarehouse returns logical (input inWarehouseNum as int64 extent 0,input inWarehouseName as character extent 0) {1}:
function readBenefits returns logical (input inEmpNum as int64 extent 0) {1}:
function readBillTo returns logical (input inBillToID as int64 extent 0,input inCustNum as int64 extent 0,input inName as character extent 0) {1}:
function readBin returns logical (input inBinNum as int64 extent 0,input inBinName as character extent 0) {1}:
function readCustomer returns logical (input inCustNum as int64 extent 0,input inComments as character extent 0,input inName as character extent 0) {1}:
function readDepartment returns logical (input inDeptCode as character extent 0,input inDeptName as character extent 0) {1}:
function readEmployee returns logical (input inEmpNum as int64 extent 0,input inFirstName as character extent 0,input inLastName as character extent 0) {1}:
function readFamily returns logical (input inEmpNum as int64 extent 0,input inRelativeName as character extent 0) {1}:
function readFeedback returns logical (input inDepartment as character extent 0,input inComments as character extent 0) {1}:
function readInventoryTrans returns logical (input inInvTransNum as int64 extent 0) {1}:
function readInvoice returns logical (input inInvoiceNum as int64 extent 0,input inAmount as decimal extent 0) {1}:
function readItem returns logical (input inItemNum as int64 extent 0,input inCatDescription as character extent 0,input inItemName as character extent 0) {1}:
function readLocalDefault returns logical (input inLocalDefNum as int64 extent 0) {1}:
function readOrder returns logical (input inCustNum as int64 extent 0,input inOrderNum as int64 extent 0) {1}:
function readOrderLine returns logical (input inLineNum as int64 extent 0,input inOrderNum as int64 extent 0) {1}:
function readPOLine returns logical (input inLineNum as int64 extent 0,input inPONum as int64 extent 0) {1}:
function readPurchaseOrder returns logical (input inPONum as int64 extent 0) {1}:
function readRefCall returns logical (input inCallNum as integer extent 0,input inCustNum as int64 extent 0,input inParent as character extent 0) {1}:
function readSalesRep returns logical (input inSalesRep as character extent 0,input inRepName as character extent 0) {1}:
function readShipTo returns logical (input inCustNum as int64 extent 0,input inShipToID as int64 extent 0,input inComments as character extent 0,input inName as character extent 0) {1}:
function readState returns logical (input inState as character extent 0,input inStateName as character extent 0) {1}:
function readSupplier returns logical (input inSupplierIDNum as int64 extent 0,input inComments as character extent 0,input inName as character extent 0,input inShipAmount as int64 extent 0) {1}:
function readSupplierItemXref returns logical (input inItemNum as int64 extent 0,input inSupplierIDNum as int64 extent 0) {1}:
function readTimeSheet returns logical (input inDayRecorded as date extent 0,input inEmpNum as int64 extent 0) {1}:
function readVacation returns logical (input inEmpNum as int64 extent 0,input inStartDate as date extent 0) {1}:
function readWarehouse returns logical (input inWarehouseNum as int64 extent 0,input inWarehouseName as character extent 0) {1}:
