http.all.authmanager=local
client.login.model=form

OEClientPrincipalFilter.domain=@DOMAIN@
OEClientPrincipalFilter.roles=EndUser
OEClientPrincipalFilter.enabled=true
OEClientPrincipalFilter.anonymous=true
OEClientPrincipalFilter.sealAnonymous=true
OEClientPrincipalFilter.passthru=true
