/* ----------------------------------------------------------------------
 File : /Procedure/record/update/general.p
 Created : 11/10/2022 20:53:18.679+00:00
 Generated by DatabaseBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

using OpenEdge.Core.Assert.

procedure updateBenefits :
   define input parameter inEmpNum as integer extent 0.

   Assert:NotZero(inEmpNum).
   find first Benefits exclusive-lock
      where Benefits.EmpNum = inEmpNum
      no-error.
   Assert:IsTrue(available Benefits). 

      assign
            Benefits.EmpNum = inEmpNum
            .
   release Benefits.
end. //Benefits

procedure updateBillTo :
   define input parameter inCustNum as integer extent 0.
   define input parameter inBillToID as integer extent 0.
   define input parameter inName as character extent 0.

   Assert:NotZero(inCustNum).
   Assert:NotZero(inBillToID).
   find first BillTo exclusive-lock
      where BillTo.BillToID = inBillToID
      and   BillTo.CustNum = inCustNum
      no-error.
   Assert:IsTrue(available BillTo). 

      assign
            BillTo.BillToID = inBillToID
            BillTo.CustNum = inCustNum
            BillTo.Name = inName
            .
   release BillTo.
end. //BillTo

procedure updateBin :
   define input parameter inBinNum as integer extent 0.
   define input parameter inBinName as character extent 0.

   Assert:NotZero(inBinNum).
   find first Bin exclusive-lock
      where Bin.BinNum = inBinNum
      no-error.
   Assert:IsTrue(available Bin). 

      assign
            Bin.BinName = inBinName
            Bin.BinNum = inBinNum
            .
   release Bin.
end. //Bin

procedure updateCustomer :
   define input parameter inCustNum as integer extent 0.
   define input parameter inName as character extent 0.
   define input parameter inComments as character extent 0.

   Assert:NotZero(inCustNum).
   find first Customer exclusive-lock
      where Customer.CustNum = inCustNum
      no-error.
   Assert:IsTrue(available Customer). 

      assign
            Customer.Comments = inComments
            Customer.CustNum = inCustNum
            Customer.Name = inName
            .
   release Customer.
end. //Customer

procedure updateDepartment :
   define input parameter inDeptCode as character extent 0.
   define input parameter inDeptName as character extent 0.

   Assert:NotEqual(inDeptCode,'').
   find first Department exclusive-lock
      where Department.DeptCode = inDeptCode
      no-error.
   Assert:IsTrue(available Department). 

      assign
            Department.DeptCode = inDeptCode
            Department.DeptName = inDeptName
            .
   release Department.
end. //Department

procedure updateEmployee :
   define input parameter inEmpNum as integer extent 0.
   define input parameter inFirstName as character extent 0.
   define input parameter inLastName as character extent 0.

   Assert:NotZero(inEmpNum).
   Assert:NotEqual(inFirstName,'').
   Assert:NotEqual(inLastName,'').
   find first Employee exclusive-lock
      where Employee.EmpNum = inEmpNum
      and   Employee.FirstName = inFirstName
      and   Employee.LastName = inLastName
      no-error.
   Assert:IsTrue(available Employee). 

      assign
            Employee.EmpNum = inEmpNum
            Employee.FirstName = inFirstName
            Employee.LastName = inLastName
            .
   release Employee.
end. //Employee

procedure updateFamily :
   define input parameter inEmpNum as integer extent 0.
   define input parameter inRelativeName as character extent 0.

   Assert:NotZero(inEmpNum).
   Assert:NotEqual(inRelativeName,'').
   find first Family exclusive-lock
      where Family.EmpNum = inEmpNum
      and   Family.RelativeName = inRelativeName
      no-error.
   Assert:IsTrue(available Family). 

      assign
            Family.EmpNum = inEmpNum
            Family.RelativeName = inRelativeName
            .
   release Family.
end. //Family

procedure updateFeedback :
   define input parameter inDepartment as character extent 0.
   define input parameter inComments as character extent 0.

   Assert:NotEqual(inDepartment,'').
   find first Feedback exclusive-lock
      where Feedback.Department = inDepartment
      no-error.
   Assert:IsTrue(available Feedback). 

      assign
            Feedback.Comments = inComments
            Feedback.Department = inDepartment
            .
   release Feedback.
end. //Feedback

procedure updateInventoryTrans :
   define input parameter inInvTransNum as integer extent 0.

   Assert:NotZero(inInvTransNum).
   find first InventoryTrans exclusive-lock
      where InventoryTrans.InvTransNum = inInvTransNum
      no-error.
   Assert:IsTrue(available InventoryTrans). 

      assign
            InventoryTrans.InvTransNum = inInvTransNum
            .
   release InventoryTrans.
end. //InventoryTrans

procedure updateInvoice :
   define input parameter inInvoiceNum as integer extent 0.
   define input parameter inAmount as decimal extent 0.

   Assert:NotZero(inInvoiceNum).
   find first Invoice exclusive-lock
      where Invoice.InvoiceNum = inInvoiceNum
      no-error.
   Assert:IsTrue(available Invoice). 

      assign
            Invoice.Amount = inAmount
            Invoice.InvoiceNum = inInvoiceNum
            .
   release Invoice.
end. //Invoice

procedure updateItem :
   define input parameter inItemNum as integer extent 0.
   define input parameter inItemName as character extent 0.
   define input parameter inCatDescription as character extent 0.

   Assert:NotZero(inItemNum).
   find first Item exclusive-lock
      where Item.ItemNum = inItemNum
      no-error.
   Assert:IsTrue(available Item). 

      assign
            Item.CatDescription = inCatDescription
            Item.ItemName = inItemName
            Item.ItemNum = inItemNum
            .
   release Item.
end. //Item

procedure updateLocalDefault :
   define input parameter inLocalDefNum as integer extent 0.

   Assert:NotZero(inLocalDefNum).
   find first LocalDefault exclusive-lock
      where LocalDefault.LocalDefNum = inLocalDefNum
      no-error.
   Assert:IsTrue(available LocalDefault). 

      assign
            LocalDefault.LocalDefNum = inLocalDefNum
            .
   release LocalDefault.
end. //LocalDefault

procedure updateOrder :
   define input parameter inOrderNum as integer extent 0.
   define input parameter inCustNum as integer extent 0.

   Assert:NotZero(inCustNum).
   Assert:NotZero(inOrderNum).
   find first Order exclusive-lock
      where Order.OrderNum = inOrderNum
      no-error.
   Assert:IsTrue(available Order). 

      assign
            Order.OrderNum = inOrderNum
            Order.CustNum = inCustNum
            .
   release Order.
end. //Order

procedure updateOrderLine :
   define input parameter inOrderNum as integer extent 0.
   define input parameter inLineNum as integer extent 0.

   Assert:NotZero(inOrderNum).
   Assert:NotZero(inLineNum).
   find first OrderLine exclusive-lock
      where OrderLine.LineNum = inLineNum
      and   OrderLine.OrderNum = inOrderNum
      no-error.
   Assert:IsTrue(available OrderLine). 

      assign
            OrderLine.LineNum = inLineNum
            OrderLine.OrderNum = inOrderNum
            .
   release OrderLine.
end. //OrderLine

procedure updatePOLine :
   define input parameter inPONum as integer extent 0.
   define input parameter inLineNum as integer extent 0.

   Assert:NotZero(inPONum).
   Assert:NotZero(inLineNum).
   find first POLine exclusive-lock
      where POLine.LineNum = inLineNum
      and   POLine.PONum = inPONum
      no-error.
   Assert:IsTrue(available POLine). 

      assign
            POLine.LineNum = inLineNum
            POLine.PONum = inPONum
            .
   release POLine.
end. //POLine

procedure updatePurchaseOrder :
   define input parameter inPONum as integer extent 0.

   Assert:NotZero(inPONum).
   find first PurchaseOrder exclusive-lock
      where PurchaseOrder.PONum = inPONum
      no-error.
   Assert:IsTrue(available PurchaseOrder). 

      assign
            PurchaseOrder.PONum = inPONum
            .
   release PurchaseOrder.
end. //PurchaseOrder

procedure updateRefCall :
   define input parameter inCallNum as integer extent 0.
   define input parameter inCustNum as integer extent 0.
   define input parameter inParent as character extent 0.

   Assert:NotZero(inCallNum).
   Assert:NotZero(inCustNum).
   Assert:NotEqual(inParent,'').
   find first RefCall exclusive-lock
      where RefCall.CallNum = inCallNum
      and   RefCall.CustNum = inCustNum
      and   RefCall.Parent = inParent
      no-error.
   Assert:IsTrue(available RefCall). 

      assign
            RefCall.CallNum = inCallNum
            RefCall.CustNum = inCustNum
            RefCall.Parent = inParent
            .
   release RefCall.
end. //RefCall

procedure updateSalesRep :
   define input parameter inSalesRep as character extent 0.
   define input parameter inRepName as character extent 0.

   Assert:NotEqual(inSalesRep,'').
   find first SalesRep exclusive-lock
      where SalesRep.SalesRep = inSalesRep
      no-error.
   Assert:IsTrue(available SalesRep). 

      assign
            SalesRep.RepName = inRepName
            SalesRep.SalesRep = inSalesRep
            .
   release SalesRep.
end. //SalesRep

procedure updateShipTo :
   define input parameter inCustNum as integer extent 0.
   define input parameter inShipToID as integer extent 0.
   define input parameter inComments as character extent 0.
   define input parameter inName as character extent 0.

   Assert:NotZero(inCustNum).
   Assert:NotZero(inShipToID).
   find first ShipTo exclusive-lock
      where ShipTo.CustNum = inCustNum
      and   ShipTo.ShipToID = inShipToID
      no-error.
   Assert:IsTrue(available ShipTo). 

      assign
            ShipTo.Comments = inComments
            ShipTo.CustNum = inCustNum
            ShipTo.Name = inName
            ShipTo.ShipToID = inShipToID
            .
   release ShipTo.
end. //ShipTo

procedure updateState :
   define input parameter inState as character extent 0.
   define input parameter inStateName as character extent 0.

   Assert:NotEqual(inState,'').
   find first State exclusive-lock
      where State.State = inState
      no-error.
   Assert:IsTrue(available State). 

      assign
            State.State = inState
            State.StateName = inStateName
            .
   release State.
end. //State

procedure updateSupplier :
   define input parameter inSupplierIDNum as integer extent 0.
   define input parameter inComments as character extent 0.
   define input parameter inName as character extent 0.
   define input parameter inShipAmount as integer extent 0.

   Assert:NotZero(inSupplierIDNum).
   find first Supplier exclusive-lock
      where Supplier.SupplierIDNum = inSupplierIDNum
      no-error.
   Assert:IsTrue(available Supplier). 

      assign
            Supplier.Comments = inComments
            Supplier.Name = inName
            Supplier.ShipAmount = inShipAmount
            Supplier.SupplierIDNum = inSupplierIDNum
            .
   release Supplier.
end. //Supplier

procedure updateSupplierItemXref :
   define input parameter inSupplierIDNum as integer extent 0.
   define input parameter inItemNum as integer extent 0.

   Assert:NotZero(inSupplierIDNum).
   Assert:NotZero(inItemNum).
   find first SupplierItemXref exclusive-lock
      where SupplierItemXref.ItemNum = inItemNum
      and   SupplierItemXref.SupplierIDNum = inSupplierIDNum
      no-error.
   Assert:IsTrue(available SupplierItemXref). 

      assign
            SupplierItemXref.ItemNum = inItemNum
            SupplierItemXref.SupplierIDNum = inSupplierIDNum
            .
   release SupplierItemXref.
end. //SupplierItemXref

procedure updateTimeSheet :
   define input parameter inEmpNum as integer extent 0.
   define input parameter inDayRecorded as date extent 0.

   Assert:NotZero(inEmpNum).
   Assert:NotNull(inDayRecorded).
   find first TimeSheet exclusive-lock
      where TimeSheet.DayRecorded = inDayRecorded
      and   TimeSheet.EmpNum = inEmpNum
      no-error.
   Assert:IsTrue(available TimeSheet). 

      assign
            TimeSheet.DayRecorded = inDayRecorded
            TimeSheet.EmpNum = inEmpNum
            .
   release TimeSheet.
end. //TimeSheet

procedure updateVacation :
   define input parameter inEmpNum as integer extent 0.
   define input parameter inStartDate as date extent 0.

   Assert:NotZero(inEmpNum).
   Assert:NotNull(inStartDate).
   find first Vacation exclusive-lock
      where Vacation.EmpNum = inEmpNum
      and   Vacation.StartDate = inStartDate
      no-error.
   Assert:IsTrue(available Vacation). 

      assign
            Vacation.EmpNum = inEmpNum
            Vacation.StartDate = inStartDate
            .
   release Vacation.
end. //Vacation

procedure updateWarehouse :
   define input parameter inWarehouseNum as integer extent 0.
   define input parameter inWarehouseName as character extent 0.

   Assert:NotZero(inWarehouseNum).
   find first Warehouse exclusive-lock
      where Warehouse.WarehouseNum = inWarehouseNum
      no-error.
   Assert:IsTrue(available Warehouse). 

      assign
            Warehouse.WarehouseName = inWarehouseName
            Warehouse.WarehouseNum = inWarehouseNum
            .
   release Warehouse.
end. //Warehouse

