/* ----------------------------------------------------------------------
 File : /Procedure/record/read/general.p
 Created : 11/10/2022 20:53:18.696+00:00
 Generated by DatabaseBuilder. - DO NOT EDIT
---------------------------------------------------------------------- */

using OpenEdge.Core.Assert.

procedure readBenefits :
   define input parameter inEmpNum as integer extent 0.

   Assert:NotZero(inEmpNum).
   find first Benefits no-lock
      where Benefits.EmpNum = inEmpNum
      no-error.
   Assert:IsTrue(available Benefits).
end. //Benefits

procedure readBillTo :
   define input parameter inCustNum as integer extent 0.
   define input parameter inBillToID as integer extent 0.

   Assert:NotZero(inCustNum).
   Assert:NotZero(inBillToID).
   find first BillTo no-lock
      where BillTo.BillToID = inBillToID
      and   BillTo.CustNum = inCustNum
      no-error.
   Assert:IsTrue(available BillTo).
end. //BillTo

procedure readBin :
   define input parameter inBinNum as integer extent 0.

   Assert:NotZero(inBinNum).
   find first Bin no-lock
      where Bin.BinNum = inBinNum
      no-error.
   Assert:IsTrue(available Bin).
end. //Bin

procedure readCustomer :
   define input parameter inCustNum as integer extent 0.

   Assert:NotZero(inCustNum).
   find first Customer no-lock
      where Customer.CustNum = inCustNum
      no-error.
   Assert:IsTrue(available Customer).
end. //Customer

procedure readDepartment :
   define input parameter inDeptCode as character extent 0.
   define input parameter inDeptName as character extent 0.

   Assert:NotEqual(inDeptCode,'').
   find first Department no-lock
      where Department.DeptCode = inDeptCode
      no-error.
   Assert:IsTrue(available Department).
end. //Department

procedure readEmployee :
   define input parameter inEmpNum as integer extent 0.

   Assert:NotZero(inEmpNum).
   find first Employee no-lock
      where Employee.EmpNum = inEmpNum
      no-error.
   Assert:IsTrue(available Employee).
end. //Employee

procedure readFamily :
   define input parameter inEmpNum as integer extent 0.
   define input parameter inRelativeName as character extent 0.

   Assert:NotZero(inEmpNum).
   Assert:NotEqual(inRelativeName,'').
   find first Family no-lock
      where Family.EmpNum = inEmpNum
      and   Family.RelativeName = inRelativeName
      no-error.
   Assert:IsTrue(available Family).
end. //Family

procedure readFeedback :
   define input parameter inDepartment as character extent 0.
   define input parameter inComments as character extent 0.

   Assert:NotEqual(inDepartment,'').
   find first Feedback no-lock
      where Feedback.Department = inDepartment
      no-error.
   Assert:IsTrue(available Feedback).
end. //Feedback

procedure readInventoryTrans :
   define input parameter inInvTransNum as integer extent 0.

   Assert:NotZero(inInvTransNum).
   find first InventoryTrans no-lock
      where InventoryTrans.InvTransNum = inInvTransNum
      no-error.
   Assert:IsTrue(available InventoryTrans).
end. //InventoryTrans

procedure readInvoice :
   define input parameter inInvoiceNum as integer extent 0.
   define input parameter inAmount as decimal extent 0.

   Assert:NotZero(inInvoiceNum).
   find first Invoice no-lock
      where Invoice.InvoiceNum = inInvoiceNum
      no-error.
   Assert:IsTrue(available Invoice).
end. //Invoice

procedure readItem :
   define input parameter inItemNum as integer extent 0.

   Assert:NotZero(inItemNum).
   find first Item no-lock
      where Item.ItemNum = inItemNum
      no-error.
   Assert:IsTrue(available Item).
end. //Item

procedure readLocalDefault :
   define input parameter inLocalDefNum as integer extent 0.

   Assert:NotZero(inLocalDefNum).
   find first LocalDefault no-lock
      where LocalDefault.LocalDefNum = inLocalDefNum
      no-error.
   Assert:IsTrue(available LocalDefault).
end. //LocalDefault

procedure readOrder :
   define input parameter inOrderNum as integer extent 0.

   Assert:NotZero(inOrderNum).
   find first Order no-lock
      where Order.OrderNum = inOrderNum
      no-error.
   Assert:IsTrue(available Order).
end. //Order

procedure readOrderLine :
   define input parameter inLineNum as integer extent 0.
   define input parameter inOrderNum as integer extent 0.

   Assert:NotZero(inLineNum).
   Assert:NotZero(inOrderNum).
   find first OrderLine no-lock
      where OrderLine.LineNum = inLineNum
      and   OrderLine.OrderNum = inOrderNum
      no-error.
   Assert:IsTrue(available OrderLine).
end. //OrderLine

procedure readPOLine :
   define input parameter inLineNum as integer extent 0.
   define input parameter inPONum as integer extent 0.

   Assert:NotZero(inLineNum).
   Assert:NotZero(inPONum).
   find first POLine no-lock
      where POLine.LineNum = inLineNum
      and   POLine.PONum = inPONum
      no-error.
   Assert:IsTrue(available POLine).
end. //POLine

procedure readPurchaseOrder :
   define input parameter inPONum as integer extent 0.

   Assert:NotZero(inPONum).
   find first PurchaseOrder no-lock
      where PurchaseOrder.PONum = inPONum
      no-error.
   Assert:IsTrue(available PurchaseOrder).
end. //PurchaseOrder

procedure readRefCall :
   define input parameter inCallNum as integer extent 0.

   Assert:NotZero(inCallNum).
   find first RefCall no-lock
      where RefCall.CallNum = inCallNum
      no-error.
   Assert:IsTrue(available RefCall).
end. //RefCall

procedure readSalesRep :
   define input parameter inSalesRep as character extent 0.
   define input parameter inRepName as character extent 0.

   Assert:NotEqual(inSalesRep,'').
   find first SalesRep no-lock
      where SalesRep.SalesRep = inSalesRep
      no-error.
   Assert:IsTrue(available SalesRep).
end. //SalesRep

procedure readShipTo :
   define input parameter inCustNum as integer extent 0.
   define input parameter inShipToID as integer extent 0.

   Assert:NotZero(inCustNum).
   Assert:NotZero(inShipToID).
   find first ShipTo no-lock
      where ShipTo.CustNum = inCustNum
      and   ShipTo.ShipToID = inShipToID
      no-error.
   Assert:IsTrue(available ShipTo).
end. //ShipTo

procedure readState :
   define input parameter inState as character extent 0.
   define input parameter inStateName as character extent 0.

   Assert:NotEqual(inState,'').
   find first State no-lock
      where State.State = inState
      no-error.
   Assert:IsTrue(available State).
end. //State

procedure readSupplier :
   define input parameter inSupplierIDNum as integer extent 0.

   Assert:NotZero(inSupplierIDNum).
   find first Supplier no-lock
      where Supplier.SupplierIDNum = inSupplierIDNum
      no-error.
   Assert:IsTrue(available Supplier).
end. //Supplier

procedure readSupplierItemXref :
   define input parameter inSupplierIDNum as integer extent 0.
   define input parameter inItemNum as integer extent 0.

   Assert:NotZero(inSupplierIDNum).
   Assert:NotZero(inItemNum).
   find first SupplierItemXref no-lock
      where SupplierItemXref.ItemNum = inItemNum
      and   SupplierItemXref.SupplierIDNum = inSupplierIDNum
      no-error.
   Assert:IsTrue(available SupplierItemXref).
end. //SupplierItemXref

procedure readTimeSheet :
   define input parameter inDayRecorded as date extent 0.
   define input parameter inEmpNum as integer extent 0.

   Assert:NotNull(inDayRecorded).
   Assert:NotZero(inEmpNum).
   find first TimeSheet no-lock
      where TimeSheet.DayRecorded = inDayRecorded
      and   TimeSheet.EmpNum = inEmpNum
      no-error.
   Assert:IsTrue(available TimeSheet).
end. //TimeSheet

procedure readVacation :
   define input parameter inEmpNum as integer extent 0.
   define input parameter inStartDate as date extent 0.

   Assert:NotZero(inEmpNum).
   Assert:NotNull(inStartDate).
   find first Vacation no-lock
      where Vacation.EmpNum = inEmpNum
      and   Vacation.StartDate = inStartDate
      no-error.
   Assert:IsTrue(available Vacation).
end. //Vacation

procedure readWarehouse :
   define input parameter inWarehouseNum as integer extent 0.

   Assert:NotZero(inWarehouseNum).
   find first Warehouse no-lock
      where Warehouse.WarehouseNum = inWarehouseNum
      no-error.
   Assert:IsTrue(available Warehouse).
end. //Warehouse

